### ISSUE TITLE
Close Websocket on Listen Verb

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#1]
Not sure if its a bug or just the way its got to be but it takes 10+ seconds for my app to close the websocket connection. 

Can you confirm that you close the socket after the listen verb ends?

**Comment by davehorton** [comment]
this shouldn't happening.  will investigate

**Comment by ajukes** [comment]
Websocket now closes instantly. Shall I close issue?

**Comment by davehorton** [comment]
fixed in v0.2.9 mod_audio_fork
