### ISSUE TITLE
NOTIFY request from SBC, returns 503, method not implemented

### ISSUE THREAD

**Issue by jugalbhavsar** [jambonz/jambonz-feature-server#1015]
Once we register with SIP, SBC is sending 503, how can we handle that?

**Comment by davehorton** [comment]
please include a pcap or drachtio log file showing the issue

**Comment by jugalbhavsar** [comment]
hi @davehorton 

Kindly refer drachtio log

2024-12-31 15:37:30.916613 nta.c:3484 agent_recv_response() nta: received 200 OK for REGISTER (93266034)
2024-12-31 15:37:31.575488 recv 1043 bytes from udp/[10.79.212.8]:5060 at 15:37:31.575389:
NOTIFY sip:+917965211500@10.54.142.90:5060;transport=udp;rinstance=9hG4bK244401 SIP/2.0
Via: SIP/2.0/UDP 10.79.212.8:5060;branch=z9hG4bK7edb0919d9cfc98f28de4e33e11380b0661e60a5-0-1c6da9-6773c2632491ce78;_aluscr_
Call-ID: LU-1735639651599213-4250479@mumumturbtas04nk.ims.ttl.in-5060-35
To: <sip:+917965211500@gj.ims.ttl.in;user=phone>
From: <sip:+917965211500@gj.ims.ttl.in;user=phone>;tag=6666ed26-6773c26323b7281f-Sxx-lucentNGFS-999999
CSeq: 1 NOTIFY
Contact: <sip:lucentNGFS-999999@mumumturbtas04nk.ims.ttl.in:5060;x-afi=35>
Content-Type: application/simservs+xml
Event: ua-profile
Max-Forwards: 68
P-Asserted-Identity: <sip:+917965211500@gj.ims.ttl.in;user=phone>
Subscription-State: active
Content-Length: 230
P-Called-Party-ID: <sip:+917965211500@gj.ims.ttl.in;user=phone>
X-LU-SkipFC: term

<?xml version="1.0" encoding="UTF-8"?>
<simservs xmlns="http://uri.etsi.org/ngn/params/xml/simservs/xcap">
<dial-tone-management>
<no-dialling-behaviour>rejectCall</no-dialling-behaviour>
</dial-tone-management>
</simservs> 
2024-12-31 15:37:31.575557 No connected clients found to handle incoming notify request
2024-12-31 15:37:31.575570 processNewRequest - No providers available for NOTIFY

**Comment by davehorton** [comment]
We do not support incoming NOTIFY.

**Comment by jugalbhavsar** [comment]
@davehorton 

Kindly guide how we can handle it?

**Comment by davehorton** [comment]
It is wrong for your client to be sending it.  There was no proceeding SUBSCRIBE that established an event subscription that could then be NOTIFIED.

jambonz does not currently support SUBSCRIBE/NOTIFY.
