### ISSUE TITLE
WS-API: using ws protocol is not possible because of an error

### ISSUE THREAD

**Issue by akirilyuk** [jambonz/jambonz-feature-server#104]
Hi,

when trying to use a unsecured websocket connection, jambonz-feature-server throws an error that the protocol is not supported, is this expected?

`
10|jambonz-feature-server  | {"level":30, "time": "2022-04-29T08:25:23.236Z","pid":6353,"hostname":"ip-10-0-19-254","callId":"c168a0f1-4238-123b-8f94-060fa1c98f14","callSid":"36eaac50-4e86-454c-9caa-083a104bc9df","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+17812856404","calledNumber":"+441603361413","traceId":"6430db61b090927f85cae6a29a05f75e","url":"ws://grauen-endpoint.eu.ngrok.io/284567ef77424421d9ae479b43df8be2ab68a2fa397ee62868b233eaca2d15a4/voiceGateway","err":{"type":"SyntaxError","message":"The URL's protocol must be one of \"ws:\", \"wss:\", or \"ws+unix:\"","stack":"SyntaxError: The URL's protocol must be one of \"ws:\", \"wss:\", or \"ws+unix:\"\n    at initAsClient (/home/admin/apps/jambonz-feature-server/node_modules/ws/lib/websocket.js:692:17)\n    at ClientRequest.<anonymous> (/home/admin/apps/jambonz-feature-server/node_modules/ws/lib/websocket.js:850:7)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)\n    at Socket.socketOnData (_http_client.js:515:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:475:12)\n    at addChunk (internal/streams/readable.js:293:12)"},"msg":"WsRequestor:request - failed connecting"}
`

The same URI works fine with a `wss://` in front.

**Comment by davehorton** [comment]
maybe try `--scheme http` ?

https://ngrok.com/docs/secure-tunnels#http-tunnels-schemes
