### ISSUE TITLE
Call not hanged up after a 487 Request Terminated from callee

### ISSUE THREAD

**Issue by juansalvatella** [jambonz/jambonz-feature-server#106]
If I place a call using Jambonz and the callee never answers I can see on the SIP traces that eventually I’ll get a 487 Request Terminated from B but that’s not being picked up by Jambonz so the call is not hanged up and hence the action hook not triggered. After the 487 the progress tone is not heard anymore and when A finally hangs up, the action hook is triggered with a dial_call_status of early-media.

**Comment by davehorton** [comment]
can you give me a simple jambonz app that illustrates this bug so I can use to recreate?

**Comment by juansalvatella** [comment]
I've tried recreating the issue without any success. I'll be closing the ticket until I can reproduce it again.
