### ISSUE TITLE
Initial Action Hook does not include a domain field when registered client

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#16]
When we have a single `applicationSid` handling multiple tenants we need to somehow distinguish who "ajukes" belongs to. For example `ajukes@test-a.viva-group.net` vs `ajukes@test-b.viva-group.net`

Currently the initial payload does not include the domain. Suggest **_originatingDomainName_** or something similar if call is initiated from registered handset

```
	direction=inbound, 
	callSid=5424cfbb-00cf-484a-a3d1-3e9fee159e24,
	accountSid=fef61e75-cec3-496c-a7bc-8368e4d02a04, 
	applicationSid=508c3a11-4b6e-41cb-b162-a87dd37a8a42, 
	from=ajukes, 
	to=07956697540,
	callerName=, 
	callId=24766c3e-faaf-1238-cca4-02b574cefade, 
	sipStatus=100, 
	callStatus=trying, 
	originatingSipIp=78.33.150.124:5060,
	originatingSipTrunkName=null, 
	...
```

**Comment by davehorton** [comment]
Would a custom header in the incoming INVITE (ie available via POST params) be sufficient?

```
X-Authenticated-User: ajukes@test-a.viva-group.net
```

**Comment by ajukes** [comment]
Yes that would be perfect!

**Comment by davehorton** [comment]
fixed
