### ISSUE TITLE
feature: ability to queue play requests for the listen verb

### ISSUE THREAD

**Issue by vcidst** [jambonz/jambonz-feature-server#201]
Currently, the applications using `listen` verb need to queue play requests and send them upon receiving a `playDone` event from Jambonz. A feature to allow applications to queue audio would be good to have, this queued audio can be played on the call one after another.

It will also be helpful for applications that wish to send the audio to Jambonz as smaller chunks (as opposed to the whole audio file). This might be the case if their audio source is a stream.

Other products of similar nature already handle this feature,
https://www.twilio.com/media-streams
https://support.exotel.com/support/solutions/articles/3000108630-working-with-the-stream-and-voicebot-applet

**Comment by xquanluu** [comment]
Hi @vcidst can you help to give an example for Jambonz Json app for this and what is your expectation for the behavior?
I'm sorry that I cannot catch the idea much.

**Comment by xquanluu** [comment]
closed as PR merged
