### ISSUE TITLE
Register User not found while sending call to Registered User

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#204]
expiry : 30 sec

first registered request with authentication successful make entry in radis with expiry time based on register expiry , after 30 sec in this case radis entry gets deleted. even the sip client send register ping it does not create new entry in radis , it creates entry after 120 sec. after 120 sec client has been challenged to registered , Any call comming before 180 sec are not connected to agent due 401 not found error. since no entry of user exist in radis

**Comment by davehorton** [comment]
fix verified
