### ISSUE TITLE
feature: hintsBoost should be array not single hintsBoost for all  hints in arrary 

### ISSUE THREAD

**Issue by vinoddh-kore** [jambonz/jambonz-feature-server#205]
Currently single hintboost value for all array elements of hints, rather each hint has to have its boost  value 

current implementation 
 
    "hints": ["weather", "support"."fair"],
    "hintsBoost": 10
  

expecting 
[
    {
      "phrases": [
        "weather"
      ],
      "boost": 18
    },
    { 
      "phrases": [
        "support",
      ],
      "boost": 2
    },
    { 
      "phrases": [
        "fair"
      ]
    },
  ]

**Comment by vinoddh-kore** [comment]
https://cloud.google.com/speech-to-text/docs/reference/rest/v1/projects.locations.phraseSets#Phrase

**Comment by davehorton** [comment]
added in 0.8.0-rc2
