### ISSUE TITLE
Bug: Wrong asr vendor name to invoke on:error event 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#214]
on providing wrong asr name , wss socket don't receive on error event 

{"level":50,"time":1673267459499,"pid":716,"hostname":"ip-172-31-10-160","callId":"4f21343a-0abc-123c-1f83-0e9f95109ce9","callSid":"148308f1-d9b0-41be-828a-efbeb94ddf7b","accountSid":"c33dd3b1-3ffb-4610-8300-4f58cb58ceb6","callingNumber":"16812213593","calledNumber":"12054174811","traceId":"7d1116e3bd07f1dc7502bf6a6e3f514c","stack":"Error: no speech-to-text service credentials for microsokjguygft have been configured\n at TaskGather.exec (/home/admin/apps/jambonz-feature-server/lib/tasks/gather.js:176:13)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async InboundCallSession.exec (/home/admin/apps/jambonz-feature-server/lib/session/call-session.js:601:11)","type":"Error","msg":"Error executing task #0:4: gather"}

**Comment by davehorton** [comment]
we should call `this.notifyError()` [here](https://github.com/jambonz/jambonz-feature-server/blob/567b03fd36b9b0fc774fe8e8170290e8c6926bf8/lib/tasks/gather.js#L166), and [here](https://github.com/jambonz/jambonz-feature-server/blob/567b03fd36b9b0fc774fe8e8170290e8c6926bf8/lib/tasks/gather.js#L388).  Check [here](https://github.com/jambonz/jambonz-feature-server/blob/567b03fd36b9b0fc774fe8e8170290e8c6926bf8/lib/tasks/gather.js#L614) for an example of how we do that.

**Comment by xquanluu** [comment]
Start working on this.

**Comment by davehorton** [comment]
fixed in [this PR](https://github.com/jambonz/jambonz-feature-server/pull/219)
