### ISSUE TITLE
No webhook request if user hangs up during early media playback

### ISSUE THREAD

**Issue by Megamuch** [jambonz/jambonz-feature-server#232]
I've found that the call status webhook is not called if a caller disconnects during an early media playback call.

The incoming webhook works, but the disconnect hook is not triggered.

**Comment by davehorton** [comment]
can you provide a log from jambonz-feature-server for such a call with loglevel debug?

**Comment by Megamuch** [comment]
`8|jambonz-feature-server  | {"level":20,"time":1674664400333,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","url":"https://jbz-media.soundofdata.app:9443/node-red/entertowin","absUrl":"https://jbz-media.soundofdata.app:9443/node-red/entertowin","hdrs":{"Jambonz-Signature":"t=1674664400,v1=add4ecd55affbdf19bad57989c92622499441b95ea849ecfd69787c4dfba1ecf","b3":"480b530e5e4b8ebf691be2fe9b6db358-51ab95312cb3e89b-1","Content-Type":"application/json"},"msg":"send webhook"}
8|jambonz-feature-server  | {"level":30,"time":1674664400369,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","response":[{"verb":"play","url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/announce.wav","earlyMedia":true,"loop":1},{"verb":"tag","data":{"roundId":1794,"did":"YYYYYYYYY","isOpen":true,"isLeadvertisement":"never","isTesting":false,"closedRate":"paid","mediaApplicationType":"entertowin","callerInterval":10,"isWinnerLeadvertisement":false,"candidateId":0,"isCandidateActive":false,"hasVotingLimit":false,"votingLimitType":0,"outboundTrunk":null,"audio":{"leadsuccess":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadsuccess.wav","leadvertisement":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadvertisement.wav","loser":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/loser1.wav","closed":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/closed.wav","intro":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/Intro.wav","hangup":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/hangup.wav","leaderror":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leaderror.wav","announce":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/announce.wav","winsuccess":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/winsuccess.wav","leadprompt":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadprompt.wav","winner":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/winner.wav"},"callStartTimeUtc":"2023-01-25T16:33:20.348Z","isWinner":false,"leadvertisement":false}},{"verb":"play","url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/Intro.wav","earlyMedia":false,"loop":1},{"verb":"play","url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/loser1.wav","earlyMedia":false,"loop":1},{"verb":"play","url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/hangup.wav","earlyMedia":false,"loop":1},{"verb":"hangup"}],"msg":"HttpRequestor:request POST https://jbz-media.soundofdata.app:9443/node-red/entertowin succeeded in 36ms"}
8|jambonz-feature-server  | {"level":20,"time":1674664400369,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","document":[{"play":{"url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/announce.wav","earlyMedia":true,"loop":1}},{"tag":{"data":{"roundId":1794,"did":"YYYYYYYYY","isOpen":true,"isLeadvertisement":"never","isTesting":false,"closedRate":"paid","mediaApplicationType":"entertowin","callerInterval":10,"isWinnerLeadvertisement":false,"candidateId":0,"isCandidateActive":false,"hasVotingLimit":false,"votingLimitType":0,"outboundTrunk":null,"audio":{"leadsuccess":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadsuccess.wav","leadvertisement":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadvertisement.wav","loser":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/loser1.wav","closed":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/closed.wav","intro":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/Intro.wav","hangup":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/hangup.wav","leaderror":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leaderror.wav","announce":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/announce.wav","winsuccess":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/winsuccess.wav","leadprompt":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/leadprompt.wav","winner":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/winner.wav"},"callStartTimeUtc":"2023-01-25T16:33:20.348Z","isWinner":false,"leadvertisement":false}}},{"play":{"url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/Intro.wav","earlyMedia":false,"loop":1}},{"play":{"url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/loser1.wav","earlyMedia":false,"loop":1}},{"play":{"url":"https://my.s3.bucket.amazonaws.com/YYYYYYYYY/hangup.wav","earlyMedia":false,"loop":1}},{"hangup":{}}],"msg":"normalizeJambones: returning document with 6 tasks"}
8|jambonz-feature-server  | {"level":30,"time":1674664400372,"pid":203988,"hostname":"ip-10-1-13-62","msg":"SessionTracker:add callSid e08ca4e8-9eac-4dad-8896-b169f0dffce7, we have 1 session being tracked"}
8|jambonz-feature-server  | {"level":20,"time":1674664400374,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","url":"https://my.application.server/callstatus","absUrl":"https://my.application.server/callstatus","hdrs":{"Jambonz-Signature":"t=1674664400,v1=2f5fffafa755d2d84e526931a88374d92e858202922f50d38044a05c23c002a1","b3":"480b530e5e4b8ebf691be2fe9b6db358-51ab95312cb3e89b-1","Content-Type":"application/json"},"msg":"send webhook"}
8|jambonz-feature-server  | {"level":30,"time":1674664400376,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","tasks":"[play:{url=https://my.s3.bucket.amazonaws.com/YYYYYYYYY/announce.wav},tag,play:{url=https://my.s3.bucket.amazonaws.com/YYYYYYYYY/Intro.wav},play:{url=https://my.s3.bucket.amazonaws.com/YYYYYYYYY/loser1.wav},play:{url=https://my.s3.bucket.amazonaws.com/YYYYYYYYY/hangup.wav},hangup]","msg":"CallSession:exec starting 6 tasks"}
8|jambonz-feature-server  | {"level":30,"time":1674664400376,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"CallSession:exec starting task #0:1: play"}
8|jambonz-feature-server  | {"level":20,"time":1674664400389,"pid":203988,"hostname":"ip-10-1-13-62","evt":{"uuid":"d97dc969-3af5-454d-8f95-14bad8bbe1fe","countOfConnections":1,"countOfChannels":0},"msg":"mediaserver 127.0.0.1 added endpoint"}
8|jambonz-feature-server  | {"level":20,"time":1674664400390,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"allocated endpoint d97dc969-3af5-454d-8f95-14bad8bbe1fe"}
8|jambonz-feature-server  | {"level":20,"time":1674664402831,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","url":"https://my.application.server/callstatus","absUrl":"https://my.application.server/callstatus","hdrs":{"Jambonz-Signature":"t=1674664402,v1=0368179fcb7a98c3f3490c374ebb2905344170f0d5a21cec0440f5eb1ac105c5","b3":"480b530e5e4b8ebf691be2fe9b6db358-51ab95312cb3e89b-1","Content-Type":"application/json"},"msg":"send webhook"}
8|jambonz-feature-server  | {"level":20,"time":1674664402831,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"play is being killed"}
8|jambonz-feature-server  | {"level":20,"time":1674664402831,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"TaskPlay:kill - killing audio"}
8|jambonz-feature-server  | {"level":30,"time":1674664402898,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"CallSession:exec completed task #0:1: play"}
8|jambonz-feature-server  | {"level":30,"time":1674664402898,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"CallSession:exec all tasks complete"}
8|jambonz-feature-server  | {"level":30,"time":1674664402898,"pid":203988,"hostname":"ip-10-1-13-62","callId":"d1da1550-1770-123c-71a0-029fb7b14c97","callSid":"e08ca4e8-9eac-4dad-8896-b169f0dffce7","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"+XXXXXXXXXX","calledNumber":"+YYYYYYYYY","traceId":"480b530e5e4b8ebf691be2fe9b6db358","msg":"InboundCallSession:_onTasksDone auto-generating non-success response to invite"}
8|jambonz-feature-server  | {"level":30,"time":1674664402900,"pid":203988,"hostname":"ip-10-1-13-62","msg":"SessionTracker:remove callSid e08ca4e8-9eac-4dad-8896-b169f0dffce7, we have 0 being tracked"}
8|jambonz-feature-server  | {"level":20,"time":1674664402964,"pid":203988,"hostname":"ip-10-1-13-62","evt":{"uuid":"d97dc969-3af5-454d-8f95-14bad8bbe1fe","countOfConnections":1,"countOfChannels":0},"msg":"mediaserver 127.0.0.1 removed endpoint"}
`

**Comment by xquanluu** [comment]
Thanks Dave, start contributing to this.

**Comment by xquanluu** [comment]
Hi @Megamuch I'm trying to reproduce the issue by integration test in the PR above, but I cannot reproduce it, after 183, the test will send CANCEL and I still see feature-server send statucCallback as expected like this:

{
  url: '/callStatus',
  headers: {
    host: '127.0.0.1:3100',
    connection: 'keep-alive',
    'Jambonz-Signature': 't=1674705445,v1=d338f71f7292223188fc60b913b32f4e88c7319b129f7dd7cd88669905470628',
    'Content-Type': 'application/json',
    'content-length': '448'
  },
  body: {
    call_sid: '62b054e1-a46b-4f8d-b411-a7ca8cbc8a23',
    direction: 'inbound',
    from: 'play_early_media',
    to: '16174000000',
    call_id: '1-1@172.38.0.10-6',
    sip_status: 487,
    sip_reason: 'Request Terminated',
    call_status: 'no-answer',
    account_sid: 'bb845d4b-83a9-4cde-a6e9-50f3743bab3f',
    trace_id: '00000000000000000000000000000000',
    application_sid: '0dddaabf-0a30-43e3-84e8-426873b1a78b',
    fs_sip_address: '172.38.0.50:5060',
    call_termination_by: 'caller'
  }
}

**Comment by xquanluu** [comment]
----------------------------------------------- 2023-01-26 03:57:25.153432
UDP message sent (595 bytes):

INVITE sip:16174000000@172.38.0.50:5060 SIP/2.0
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: <sip:16174000000@172.38.0.50:5060>
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 INVITE
Contact: sip:play_early_media@172.38.0.10:5060
Max-Forwards: 70
X-Account-Sid: bb845d4b-83a9-4cde-a6e9-50f3743bab3f
Subject: uac-say
Content-Type: application/sdp
Content-Length:   133

v=0
o=user1 53655765 2353687637 IN IP4 172.38.0.10
s=-
c=IN IP4 172.38.0.10
t=0 0
m=audio 6000 RTP/AVP 0
a=rtpmap:0 PCMU/8000

----------------------------------------------- 2023-01-26 03:57:25.157799
UDP message received [272] bytes :

SIP/2.0 100 Trying
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0;rport=5060
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: <sip:16174000000@172.38.0.50:5060>
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 INVITE
Content-Length: 0


----------------------------------------------- 2023-01-26 03:57:25.288403
UDP message received [566] bytes :

SIP/2.0 183 Session in Progress
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0;rport=5060
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: <sip:16174000000@172.38.0.50:5060>;tag=tF1Q361c7NtUa
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 INVITE
Content-Type: application/sdp
Content-Length: 230

v=0
o=FreeSWITCH 1674667629 1674667630 IN IP4 172.38.0.51
s=FreeSWITCH
c=IN IP4 172.38.0.51
t=0 0
m=audio 37816 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv

----------------------------------------------- 2023-01-26 03:57:25.293059
UDP message sent (349 bytes):

CANCEL sip:16174000000@172.38.0.50:5060 SIP/2.0
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: 16174000000 <sip:16174000000@172.38.0.50:5060>
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 CANCEL
Contact: sip:play_early_media@172.38.0.10:5060
Max-Forwards: 70


----------------------------------------------- 2023-01-26 03:57:25.294754
UDP message received [298] bytes :

SIP/2.0 200 OK
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0;rport=5060
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: 16174000000 <sip:16174000000@172.38.0.50:5060>;tag=tF1Q361c7NtUa
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 CANCEL
Content-Length: 0


----------------------------------------------- 2023-01-26 03:57:25.297307
UDP message received [302] bytes :

SIP/2.0 487 Request Terminated
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-0;rport=5060
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: <sip:16174000000@172.38.0.50:5060>;tag=tF1Q361c7NtUa
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 INVITE
Content-Length: 0


----------------------------------------------- 2023-01-26 03:57:25.298291
UDP message sent (398 bytes):

ACK sip:16174000000@172.38.0.50:5060 SIP/2.0
Via: SIP/2.0/UDP 172.38.0.10:5060;branch=z9hG4bK-1-1-7
From: play_early_media <sip:play_early_media@172.38.0.10:5060>;tag=1SIPpTag001
To: 16174000000 <sip:16174000000@172.38.0.50:5060>;tag=tF1Q361c7NtUa
Call-ID: 1-1@172.38.0.10-6
CSeq: 1 ACK
Contact: sip:play_early_media@172.38.0.10:5060
Max-Forwards: 70
Subject: uac-say
Content-Length: 0

**Comment by Megamuch** [comment]
@xquanluu let me work on getting you the proper information. Expect an update in 24 hours.

**Comment by Megamuch** [comment]
@xquanluu I've confirmed this works as intended. I will close this one.
