### ISSUE TITLE
unit tests for WsRequestor

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#237]
We don't have any test coverage of [WsRequestor](https://github.com/jambonz/jambonz-feature-server/blob/main/lib/utils/ws-requestor.js) and since this class is importable and pretty self-contained it should be possible to write some unit test cases where we mock the websocket server side of things.  The goal would be to get > 80% test coverage.  Can we use sinon.js or something like that for the mock?

**Comment by xquanluu** [comment]
Thanks Dave, Start contributing to this.
