### ISSUE TITLE
Bug: SSML with mp3 file not working for nunace

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#248]
<speak><audio src=\"https://file-examples.com/storage/feeb72b10363daaeba4c0c9/2017/11/file_example_MP3_700KB.mp3\"></audio> </speak>

get error {"code":400,"message":"Bad Request","details":"Failed to synthesize text: TTS_E_SSML_PARSE_ERROR"},"msg":"Error synthesizing tts"}

**Comment by xquanluu** [comment]
Hi All,

I don't get the context of issue, @vdharashive it's great if you can give me more hint to reproduce the issue?

**Comment by davehorton** [comment]
the issue is just that when call synthAudio with SSML below it fails, even though it is valid SSML
```
<audio src="[https://file-examples.com/storage/feeb72b10363daaeba4c0c9/2017/11/file_example_MP3_700KB.mp3\">](https://file-examples.com/storage/feeb72b10363daaeba4c0c9/2017/11/file_example_MP3_700KB.mp3%5C%22%3E)
```

**Comment by davehorton** [comment]
we should add a test case for this in realtime-dbhelpers first, to see if it does indeed fail

**Comment by davehorton** [comment]
Hmm, it looks to me like Nuance only supports wav files

https://docs.nuance.com/mix/apis/tts-grpc/v1/ref-topics/input-tts/#audio

**Comment by vdharashive** [comment]
wav also not working checking,checking with nuance

**Comment by davehorton** [comment]
closed due to lack of information
