### ISSUE TITLE
bug : continuous asr not working for azure and nuance

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#249]

**Comment by davehorton** [comment]
logs please

**Comment by davehorton** [comment]
I'm fairly sure continuous asr **does** work for azure, so a set of logs will be necessary.

**Comment by vdharashive** [comment]
for azure it work, the result is array , which needs to be merged , i am not sure if this needs to be handled at jambonz, but i have handled it at application end. 
logs :
{
  "level": 20,
  "time": 1675847884747,
  "pid": 1099185,
  "hostname": "ip-172-31-27-212",
  "callId": "501772b9-2234-123c-23a5-0e04dbeb38cf",
  "callSid": "d80fe64c-77f1-4ccf-944e-430fac6a3b89",
  "accountSid": "8fbd67ab-746f-440d-9d9a-3650dd7062ae",
  "callingNumber": "vikram",
  "calledNumber": "+12055480588",
  "traceId": "d65408a2656184bb1efd795b6b52e421",
  "obj": {
    "type": "verb:hook",
    "msgid": "dk2ZHJHXHUnqsH6vxzVxG6",
    "call_sid": "d80fe64c-77f1-4ccf-944e-430fac6a3b89",
    "hook": "/actions/hooks",
    "data": {
      "call_sid": "d80fe64c-77f1-4ccf-944e-430fac6a3b89",
      "direction": "inbound",
      "from": "vikram",
      "to": "+12055480588",
      "call_id": "501772b9-2234-123c-23a5-0e04dbeb38cf",
      "sip_status": 200,
      "sip_reason": "OK",
      "call_status": "in-progress",
      "account_sid": "8fbd67ab-746f-440d-9d9a-3650dd7062ae",
      "trace_id": "d65408a2656184bb1efd795b6b52e421",
      "application_sid": "90d6c4dd-be3c-4272-a8ba-7dc4b0dbce41",
      "fs_sip_address": "172.31.27.212:5070",
      "originating_sip_ip": "3.220.66.149",
      "originating_sip_trunk_name": "Vikram",
      "customerData": {
        "userNoInputCounter": 1,
        "retryCount": 3
      },
      "api_base_url": "http://54.144.17.110/v1",
      "speech": {
        "is_final": true,
        "transcripts": [
          {
            "language_code": "en-IN",
            "channel_tag": 1,
            "is_final": true,
            "alternatives": [
              {
                "confidence": 0.80972123,
                "transcript": "Yeah"
              }
            ],
            "vendor": {
              "name": "microsoft",
              "evt": {
                "id": "cb75e560b2124fbf9d766533c0bb8b64",
                "recognition_status": "Success",
                "offset": 2200000,
                "duration": 3000000,
                "channel": 0,
                "display_text": "Yeah.",
                "n_best": [
                  {
                    "confidence": 0.80972123,
                    "lexical": "yeah",
                    "itn": "yeah",
                    "masked_i_t_n": "yeah",
                    "display": "Yeah.",
                    "words": [
                      {
                        "word": "yeah",
                        "offset": 2200000,
                        "duration": 3000000,
                        "confidence": 0.80972123
                      }
                    ]
                  },
                  {
                    "confidence": 0.86791676,
                    "lexical": "yes",
                    "itn": "yes",
                    "masked_i_t_n": "yes",
                    "display": "yes",
                    "words": [
                      {
                        "word": "yes",
                        "offset": 2200000,
                        "duration": 2800000,
                        "confidence": 0.86791676
                      }
                    ]
                  },
                  {
                    "confidence": 0.6647969,
                    "lexical": "you",
                    "itn": "you",
                    "masked_i_t_n": "you",
                    "display": "you",
                    "words": [
                      {
                        "word": "you",
                        "offset": 2200000,
                        "duration": 2900000,
                        "confidence": 0.6647969
                      }
                    ]
                  },
                  {
                    "confidence": 0.54926634,
                    "lexical": "yep",
                    "itn": "yep",
                    "masked_i_t_n": "yep",
                    "display": "yep",
                    "words": [
                      {
                        "word": "yep",
                        "offset": 2200000,
                        "duration": 2800000,
                        "confidence": 0.54926634
                      }
                    ]
                  },
                  {
                    "confidence": 0.61964,
                    "lexical": "s",
                    "itn": "s",
                    "masked_i_t_n": "s",
                    "display": "s",
                    "words": [
                      {
                        "word": "s",
                        "offset": 2200000,
                        "duration": 2800000,
                        "confidence": 0.61964
                      }
                    ]
                  }
                ]
              }
            }
          },
          {
            "language_code": "en-IN",
            "channel_tag": 1,
            "is_final": true,
            "alternatives": [
              {
                "confidence": 0.9482992,
                "transcript": "My name is"
              }
            ],
            "vendor": {
              "name": "microsoft",
              "evt": {
                "id": "276a516625114e609557fceec0b3e96b",
                "recognition_status": "Success",
                "offset": 20800000,
                "duration": 6800000,
                "channel": 0,
                "display_text": "My name is.",
                "n_best": [
                  {
                    "confidence": 0.9482992,
                    "lexical": "my name is",
                    "itn": "my name is",
                    "masked_i_t_n": "my name is",
                    "display": "My name is.",
                    "words": [
                      {
                        "word": "my",
                        "offset": 20800000,
                        "duration": 3100000,
                        "confidence": 0.9373648
                      },
                      {
                        "word": "name",
                        "offset": 24000000,
                        "duration": 2800000,
                        "confidence": 0.97379804
                      },
                      {
                        "word": "is",
                        "offset": 26900000,
                        "duration": 700000,
                        "confidence": 0.89960396
                      }
                    ]
                  },
                  {
                    "confidence": 0.9092172,
                    "lexical": "my name",
                    "itn": "my name",
                    "masked_i_t_n": "my name",
                    "display": "my name",
                    "words": [
                      {
                        "word": "my",
                        "offset": 20800000,
                        "duration": 3100000,
                        "confidence": 0.9373648
                      },
                      {
                        "word": "name",
                        "offset": 24000000,
                        "duration": 3600000,
                        "confidence": 0.8848733
                      }
                    ]
                  },
                  {
                    "confidence": 0.9179538,
                    "lexical": "my name in",
                    "itn": "my name in",
                    "masked_i_t_n": "my name in",
                    "display": "my name in",
                    "words": [
                      {
                        "word": "my",
                        "offset": 20800000,
                        "duration": 3100000,
                        "confidence": 0.9373648
                      },
                      {
                        "word": "name",
                        "offset": 24000000,
                        "duration": 3000000,
                        "confidence": 0.97674286
                      },
                      {
                        "word": "in",
                        "offset": 27100000,
                        "duration": 500000,
                        "confidence": 0.5106848
                      }
                    ]
                  },
                  {
                    "confidence": 0.8267893,
                    "lexical": "my name i",
                    "itn": "my name i",
                    "masked_i_t_n": "my name i",
                    "display": "my name i",
                    "words": [
                      {
                        "word": "my",
                        "offset": 20800000,
                        "duration": 3100000,
                        "confidence": 0.9373648
                      },
                      {
                        "word": "name",
                        "offset": 24000000,
                        "duration": 3300000,
                        "confidence": 0.748286
                      },
                      {
                        "word": "i",
                        "offset": 27400000,
                        "duration": 200000,
                        "confidence": 0.53702164
                      }
                    ]
                  },
                  {
                    "confidence": 0.90326315,
                    "lexical": "my name it",
                    "itn": "my name it",
                    "masked_i_t_n": "my name it",
                    "display": "my name it",
                    "words": [
                      {
                        "word": "my",
                        "offset": 20800000,
                        "duration": 3100000,
                        "confidence": 0.9373648
                      },
                      {
                        "word": "name",
                        "offset": 24000000,
                        "duration": 3000000,
                        "confidence": 0.97674286
                      },
                      {
                        "word": "it",
                        "offset": 27100000,
                        "duration": 500000,
                        "confidence": 0.34174347
                      }
                    ]
                  }
                ]
              }
            }
          }
        ]
      },
      "reason": "speechDetected"
    },
    "b3": "d65408a2656184bb1efd795b6b52e421-be2735150363dd0b-1"
  },
  "msg": "WsRequestor:request websocket: sent (/actions/hooks)"
}

**Comment by davehorton** [comment]
yes, this is by intent -- jambonz reports the individual utterances in an array, so you need to combine as appropriate

**Comment by vdharashive** [comment]
Ok fine got it
