### ISSUE TITLE
bug : interDigitTimeout is not working as expected

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#250]
**interDigitTimeout value set to 2 seconds after waiting for 2 second it should send dtmf value to webhook instead it sending timeout** 

{"level":20,"time":1675781011369,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","command":"redirect","call_sid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","queueCommand":true,"data":[{"verb":"config","synthesizer":{"vendor":"aws","voice":"Joanna","language":"en-US"},"recognizer":{"vendor":"google","language":"en-IN"}},{"verb":"tag","data":{"userNoInputCounter":1,"retryCount":3}},{"verb":"gather","actionHook":"/actions/hooks","input":["digits","speech"],"interDigitTimeout":2,"finishOnKey":"#","numDigits":12,"say":{"text":"Thank you for calling us. I’m an automated assistant powered by Smart assist. please press 1 to talk to Agent"},"bargein":true,"timeout":5,"dtmfBargein":true}],"msg":"received command"}

59|jambonz-feature-server  | {"level":30,"time":1675781011369,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","command":"redirect","queueCommand":true,"msg":"CallSession:_onCommand - received command"}
59|jambonz-feature-server  | {"level":20,"time":1675781020312,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","dtmf":"1","duration":"2080","source":"RTP","msg":"TaskGather:_onDtmf"}
59|jambonz-feature-server  | {"level":20,"time":1675781020312,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","msg":"say is being killed"}
59|jambonz-feature-server  | {"level":20,"time":1675781020312,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","msg":"TaskSay:kill - killing audio"}
59|jambonz-feature-server  | {"level":20,"time":1675781021487,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","msg":"TaskGather:_onEndOfUtterance"}
59|jambonz-feature-server  | {"level":20,"time":1675781021487,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","msg":"Gather:_killAudio: killing playback of any audio"}
59|jambonz-feature-server  | {"level":20,"time":1675781021487,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","vendor":"google","locale":"en-IN","interim":true,"bugname":"google_transcribe","msg":"Gather:_startTranscribing"}
59|jambonz-feature-server  | {"level":20,"time":1675781022983,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","msg":"TaskGather:resolve with reason timeout"}

59|jambonz-feature-server  | {"level":20,"time":1675781022984,"pid":1048037,"hostname":"ip-172-31-27-212","callId":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","callSid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","accountSid":"fa074283-07f8-4793-879f-6f069c9df238","callingNumber":"ramanaathan","calledNumber":"+12029533648","traceId":"3add67258313bdf5ccc002eabc62c7e7","obj":{"type":"verb:hook","msgid":"qxZ1ciNmCDCWLrZGGMge2P","call_sid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","hook":"/actions/hooks","data":{"call_sid":"af835826-4cd6-49ac-ace3-8a94ac7b322d","direction":"inbound","from":"ramanaathan","to":"+12029533648","call_id":"a0e3a9ef-2198-123c-23a5-0e04dbeb38cf","sip_status":200,"sip_reason":"OK","call_status":"in-progress","account_sid":"fa074283-07f8-4793-879f-6f069c9df238","trace_id":"3add67258313bdf5ccc002eabc62c7e7","application_sid":"670a185f-396f-4a86-8979-8c922ef7fa58","fs_sip_address":"172.31.27.212:5070","originating_sip_ip":"3.220.66.149","originating_sip_trunk_name":"Ramanaathan","customerData":{"userNoInputCounter":1,"retryCount":3},"api_base_url":"http://54.144.17.110/v1","reason":"timeout"},"b3":"3add67258313bdf5ccc002eabc62c7e7-bffd49f517685f58-1"},"msg":"WsRequestor:request websocket: sent (/actions/hooks)"}

**Comment by davehorton** [comment]
This looks like the log file has been edited -- stuff is missing.  For instance, we see a play command killed that was never started in the log.  This ticket will remain idle until we have a complete log file - if you need to redact, do so but do not remove any lines

**Comment by vdharashive** [comment]
enclosed the logs 
[interDigitTimeout.txt](https://github.com/jambonz/jambonz-feature-server/files/10679388/interDigitTimeout.txt)

**Comment by vinoddh-kore** [comment]
its works

**Comment by vdharashive** [comment]
Close this issue
