### ISSUE TITLE
Feature Server restarts after call update

### ISSUE THREAD

**Issue by AFelix53** [jambonz/jambonz-feature-server#251]
While performing an outbound call, if we attempt to end it before it is answered by updating the call via REST API to a 'no-answer' state, feature-server simply throws a ClientDestroyedError and restarts. 

Reproduction steps:

1. place outbound call
2. update call to `{ call_status: 'no-answer' }`
3. at this point FS just restarts

Included logs with multiple occurences 

[fs-20230207.txt](https://github.com/jambonz/jambonz-feature-server/files/10678681/fs-20230207.txt)

**Comment by AFelix53** [comment]
The error appears to be thrown on the `_notifyCallStatusChange` method of CallSession.

The fact the `this.notifier.request` call is not being awaited causes the error to not be caught by the encapsulating try catch.

Not sure what exactly causes the error, but this is probably why the FS is restarting.

**Comment by davehorton** [comment]
what version was this?

**Comment by AFelix53** [comment]
v0.7.9

**Comment by davehorton** [comment]
fixed in v0.7.13 and v0.8.0-rc11
