### ISSUE TITLE
Bug: Audio call getting disconnected in 20 sec for  webrtc to webrtc call

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#259]
57|sbc-inbound             | {"level":50, "time": "2023-02-10T07:31:49.610Z","pid":1153743,"hostname":"ip-172-31-27-212","callId":"8j6vgh5vmnu4ijni2anc","err":{"type":"SipError","message":"Sip non-success response: 488","stack":"SipError: Sip non-success response: 488\n    at Request.<anonymous> (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/dialog.js:363:26)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at DrachtioAgent._onMsg (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/drachtio-agent.js:686:22)\n    at WireProtocol.emit (node:events:513:28)\n    at WireProtocol.emit (node:domain:489:12)\n    at WireProtocol.processMessageBuffer (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/wire-protocol.js:293:12)\n    at WireProtocol._onData (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/wire-protocol.js:326:14)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)","name":"SipError","status":488,"reason":"Not Acceptable Here"},"msg":"Error handling reinvite"}

**Comment by vdharashive** [comment]
Enclosed log file 
[webrtc-20sec.txt](https://github.com/jambonz/jambonz-feature-server/files/10704950/webrtc-20sec.txt)

**Comment by davehorton** [comment]
can you also provide the drachtio log file from the sbc-sip?

**Comment by vinoddh-kore** [comment]
logs enclosed as requested

[drachtio.log](https://github.com/jambonz/jambonz-feature-server/files/10740220/drachtio.log)
[application.log](https://github.com/jambonz/jambonz-feature-server/files/10740223/application.log)

**Comment by vdharashive** [comment]
this issue has been fixed
