### ISSUE TITLE
deprecated dependency of UUID package inside docker container

### ISSUE THREAD

**Issue by radicaldrew** [jambonz/jambonz-feature-server#26]
When running the feature server inside of docker container by itself I receive an error with several files
related to the uuid package.      The latest version of uuid does not support Deep Requires and the require
has changed.  I have forked the repo and have fixed on my end by replacing the requires.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /usr/src/app/node_modules/uuid/package.json

I can submit a pull request for this.

**Comment by radicaldrew** [comment]
Created new pull request for this issue: #27

**Comment by davehorton** [comment]
Thanks for the pull request on this.  Are you trying to run jambonz in a docker environment?  If so I would be interested in your progress on this, as I have not had time to focus on this myself but am interested.  Would love to hear more about your experience (email me at daveh at drachtio.org)
