### ISSUE TITLE
Dailout from jambonz in tromboning does not use information from inbound call

### ISSUE THREAD

**Issue by Megamuch** [jambonz/jambonz-feature-server#277]
I've noticed something in the following scenario and I would like to know if this is something that should be handling by jambonz or in node red. 

call scenario: 
inbound call with anonymous from header, with PAI filled out. 
Call is handled by a node red application which does a dialout to a pstn destination. 
On the dialout node in node red we use the from header information to forward the call. 

The call is then passed to the carrier and the call is forwarded. However, the PAI is no longer in the INVITE going to the carrier. the information is not transferred to the outdial object. 

In the case of an anonymous call, this will mean that the outdial invite contains no identifiable information (since the from is anonymous and there is no PAI), and thus the call will be rejected by the carrier.

To circumvent this, we inject the PAI into the outdial headers within node red. This works. 
I would prefer to keep this logic "away" from the app builders and make this happen by default to keep the node red flows clean.
I do not want to burden app developers with the details of setting pai headers.

So the question is, is there a way to make this happen either within jbz or through node red dailout config by default.

**Comment by xquanluu** [comment]
Checking issue now

**Comment by davehorton** [comment]
fixed and merged
