### ISSUE TITLE
Alert freeswitch errors caused by STT provider errors

### ISSUE THREAD

**Issue by javibookline** [jambonz/jambonz-feature-server#279]
Build: k8s - release v0.8.1

Currently there are some errors caught by the freeswitch container of the feature-server deployment which go unnoticed. One example is an error raised when a request with invalid config is sent to Google STT, which results in the following freeswitch error message

`[ERR] google_glue.cpp:391 grpc_read_thread: error Invalid recognition 'config': The requested model is currently not supported for language : es-MX. (3)`

In this case, the request specified the default model `latest_short` chosen by jambonz feature-server, which in combination with the application-specified language `es-MX` results in an invalid STT config.

This error in particular kills the gather verb that created the request but does not alert of any error, so it may go unnoticed unless someone is actively monitoring it.

It would be nice to log/notify alerts related to these errors, or at least give them more visibility.

**Comment by davehorton** [comment]
Note that in the latest freeswitch modules we now are returning the error to the gather/transcribe verb, so this should be a matter of writing alerts @xquanluu
