### ISSUE TITLE
no status event is thrown to notify that an outbound call has ended if the caller hangs up while the outbound leg is still ringing

### ISSUE THREAD

**Issue by GlennS83** [jambonz/jambonz-feature-server#281]
I've been testing around with status events from my jambonz application but it seems I do not receive a 'failed' or 'no-answer' event for an outbound call if the the caller, who instantiated the dial, disconnects before the outbound destination answers. I see the following sequence of events when I'm testing:

    Received inbound active call status event of type: trying for callId 6df26ca3-41c9-123c-2087-0a3949153b1f (call is instantiated)
    Received inbound active call status event of type: in-progress for callId 6df26ca3-41c9-123c-2087-0a3949153b1f (call is answered & a dial is executed)
    Received outbound active call status event of type: trying for callId 73158ed0-41c9-123c-a6b1-02a2c796aedb <= THIS IS WHERE THE CALLER HANGS UP
    Received outbound active call status event of type: ringing for callId 73158ed0-41c9-123c-a6b1-02a2c796aedb
    Received outbound active call status event of type: ringing for callId 73158ed0-41c9-123c-a6b1-02a2c796aedb
    Received outbound active call status event of type: ringing for callId 73158ed0-41c9-123c-a6b1-02a2c796aedb
    Received inbound active call status event of type: completed for callId 6df26ca3-41c9-123c-2087-0a3949153b1f

**Comment by xquanluu** [comment]
Hi @GlennS83 Could you please share me jambonz json application for this issue?

**Comment by xquanluu** [comment]
I'm closing this issue due to no response
