### ISSUE TITLE
feature : Dial Verb to have callername/From for Type User,sip

### ISSUE THREAD

**Issue by vinoddh-kore** [jambonz/jambonz-feature-server#289]
Current there is no way we can set caller name / From  in the dial function for type user and sip 
eg : From : "Tom " <sip:9455444@xyz.com>
    
Currently when callerid is set to any name, it goes as anyominous

**Comment by davehorton** [comment]
@xquanluu can this be closed?

**Comment by vinoddh-kore** [comment]
it working
