### ISSUE TITLE
Twilio SipRec Transcript not generating for outbound leg

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#297]
Transcript are getting geneartated for inbound leg but not for outbound leg

freeswitch show only inbound leg transcripts are happening 

also jambonz is responding sdp packet for RTP as sendrecv rather it should be recvonly  

Via: SIP/2.0/UDP 54.172.60.0:5060;branch=z9hG4bK1114.675fd841d5f9c41e2984636268fca7ad.0;rport=5060
Via: SIP/2.0/UDP 172.25.51.50:5060;rport=5060;branch=z9hG4bKd314f63a-36c4-4e0d-8bb4-84a7504b65ec_c3356d0b_626-5153984073030224992
Record-Route: <sip:54.172.60.0;lr>
From: <sip:SRC@sip.twilio.com>;tag=20581391_c3356d0b_d314f63a-36c4-4e0d-8bb4-84a7504b65ec
To: <sip:5510103@23.21.52.56:5060>;tag=6SU84K9g3r2rj
Call-ID: 4bee7de2200e9d12b6995daf530eb04a@0.0.0.0
CSeq: 1 INVITE
Contact: <sip:23.21.52.56:5060>
Content-Type: application/sdp
Content-Length: 411
X-Call-Sid: 9176ad59-b814-4f0f-b47f-4e6a98fbe7c3
X-Application-Sid: 248bdaca-762b-46d0-9d40-f098954f4f17

v=0
o=FreeSWITCH 1680510659 1680510660 IN IP4 18.232.141.81
s=FreeSWITCH
c=IN IP4 18.232.141.81
t=0 0
m=audio 10200 RTP/AVP 0 101
a=label:1
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
**a=sendrecv**
a=rtcp:10201
a=ptime:20
m=audio 10230 RTP/AVP 0 101
a=label:2
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
**a=sendrecv**
a=rtcp:10231
a=ptime:20

[FS.txt](https://github.com/jambonz/jambonz-feature-server/files/11141153/FS.txt)
[SBC.txt](https://github.com/jambonz/jambonz-feature-server/files/11141155/SBC.txt)
[Freeswitch.log](https://github.com/jambonz/jambonz-feature-server/files/11141158/Freeswitch.log)
[SBC-SIP.log](https://github.com/jambonz/jambonz-feature-server/files/11141165/SBC-SIP.log)

**Comment by davehorton** [comment]
This is likely because you specified "mixType": "mixed".  That will create a single stream with both audio channels mixed.  Please try mixType: "stereo"
