### ISSUE TITLE
X-Authenticated-User is not passed to webhook

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#301]
`X-Authenticated-User` is not passed to initial webhook when a registered user creates a call. 

Worked in 0.7.9 but not in 0.8.2

**Comment by davehorton** [comment]
@ajukes are you talking of a rest create call?  Can you share the payload?

**Comment by ajukes** [comment]
No a registered device sending an invite to Jambonz SBC

```
INVITE sip:0044XXXXXXX@callabletest.foo.bar
```

**Comment by xquanluu** [comment]
Hi @ajukes From what I understand that Feature server will copy SIP INVITE request to webhook without modification or remove any header.
X-Authenticated-User sip header is being added by sbc-inbound when authentication successfully with device.

Can you capture and share the pcap to see the INVITE request from sbc-inbound to feature server contains X-Authenticated-User ?

I tested both site sbc-inbound and feature server, they are all working perfectly.

**Comment by xquanluu** [comment]
Closed as PR is fixed, Thanks @ajukes  for your help.
