### ISSUE TITLE
span.end() called multiple times on same span

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#315]
The following code in `lib/middleware.js` causes RootSpan.end() to be called multiple times on same span. Opentelementry swallows the error but it raises a point that for a 487 CANCEL, both `cancel` and `finish` callbacks are invoked

```
/**
     * end the span on final failure or cancel from caller;
     * otherwise it will be closed when sip dialog is destroyed
     */
    req.once('cancel', () => {
      rootSpan.setAttributes({finalStatus: 487});
      rootSpan.end();
    });
    res.once('finish', () => {
      rootSpan.setAttributes({finalStatus: res.statusCode});
      res.statusCode >= 300 && rootSpan.end();
    });
```

**Comment by xquanluu** [comment]
Start working on this.

**Comment by xquanluu** [comment]
Hi @ajukes I'm trying to reproduce the issue by this testcase:
https://github.com/jambonz/jambonz-feature-server/blob/main/test/play-tests.js#L204

But I don't see that both call back are call in case of cancel - 487

**Comment by ajukes** [comment]
Will have a look and come back to you
