### ISSUE TITLE
awselb needs user-agent header mandatory for http and wss

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#317]
6|jambonz-feature-server  | {"level":30,"time":1681490966377,"pid":878525,"hostname":"ip-172-31-11-177","callId":"284cdc42-5587-123c-75a7-0e9f95109ce9","callSid":"603fc6f5-8fe5-4efe-9aab-79f109165deb","accountSid":"3978e7ef-e014-4a9e-9184-ff24a19d9fad","callingNumber":"+646454645","calledNumber":"+45345354","traceId":"9dab3e969562bd488c82990881026331","headers":{"server":"awselb/2.0","date":"Fri, 14 Apr 2023 16:49:26 GMT","content-type":"text/html","content-length":"118","connection":"keep-alive"},"statusCode":403,"statusMessage":"Forbidden","msg":"WsRequestor - unexpected response"}

**Comment by davehorton** [comment]
please provide more details when opening an issue.  Not really clear on this, not enough info to start working on it.

**Comment by vdharashive** [comment]
Ill fix this issue  and Raise PR 

reference 
https://repost.aws/knowledge-center/waf-block-http-requests-no-user-agent

**Comment by davehorton** [comment]
can you make PR?
