### ISSUE TITLE
AMD support for CreateCall API

### ISSUE THREAD

**Issue by vinoddh-kore** [jambonz/jambonz-feature-server#328]
its important to detect amd for for all outbound call, and action  needs to define what action to taken if and detected either Hangup call or continue to call to handle.

**Comment by davehorton** [comment]
you can achieve this by having your webhook return an application that has a [config verb with an amd ](https://www.jambonz.org/docs/webhooks/config/)property.

**Comment by vinoddh-kore** [comment]
Handled at bot level as suggested
