### ISSUE TITLE
Add support for Deepgram option 'endpointing'

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#329]
Enhance verb-specifications, jambonz-feature-server, and mod_deepgram_transcribe to support a new option in recognizer.deepgramOptions called 'endpointing'.

Described [here](https://developers.deepgram.com/documentation/features/endpointing/).

**Comment by xquanluu** [comment]
Start working on this

**Comment by xquanluu** [comment]
Closed this as PRs all merged
