### ISSUE TITLE
Bug: REST update call timing issue

### ISSUE THREAD

**Issue by two56** [jambonz/jambonz-feature-server#333]
Reproduce issue:

1. Place a REST call to update the `call_hook` while an existing `actionHook` is in-flight.
2. Place a REST call to update the `call_hook` just before an existing `actionHook` is about to take flight but the updated `call_hook` hasn't responded.

Behaviour:

1. There's a race condition in both cases giving unpredictable results.

Expected behaviour:

The updated `call_hook` overrides any in-flight or about to take flight webhooks.

**Comment by davehorton** [comment]
Thanks, I believe you were going to make a PR for this @two56 ?
