### ISSUE TITLE
Bug Nvida asr tts not working

### ISSUE THREAD

**Issue by vinoddh-kore** [jambonz/jambonz-feature-server#340]
getting below error No speech-to-text service credentials for nvidia have been configured

{
  "level": 30,
  "time": 1683547551806,
  "pid": 1486701,
  "hostname": "ip-172-20-11-142",
  "callId": "84b3b71d-683b-123c-cd93-0e5efc2d5183",
  "callSid": "fe5bdbc3-2168-40dd-a0a8-6c1105491165",
  "accountSid": "4299cf4b-a218-4a27-8ce0-f4d8354bc1c9",
  "callingNumber": "Niki",
  "calledNumber": "9323760394",
  "traceId": "668b6cb41bf55a8b742b1612ee649f03",
  "msg": "TaskGather:exec - ERROR stt using nvidia requested but creds not supplied"
}11|savgw-feature-server|{
  "level": 50,
  "time": 1683547551807,
  "pid": 1486701,
  "hostname": "ip-172-20-11-142",
  "callId": "84b3b71d-683b-123c-cd93-0e5efc2d5183",
  "callSid": "fe5bdbc3-2168-40dd-a0a8-6c1105491165",
  "accountSid": "4299cf4b-a218-4a27-8ce0-f4d8354bc1c9",
  "callingNumber": "Niki",
  "calledNumber": "9323760394",
  "traceId": "668b6cb41bf55a8b742b1612ee649f03",
  "err": {
    "type": "Error",
    "message": "No speech-to-text service credentials for nvidia have been configured",
    "stack": "Error: No speech-to-text service credentials for nvidia have been configured\n    at TaskGather.exec (/home/admin/apps/savgw-feature-server/lib/tasks/gather.js:205:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InboundCallSession.exec (/home/admin/apps/savgw-feature-server/lib/session/call-session.js:734:11)"
  }

**Comment by vinoddh-kore** [comment]
https://github.com/jambonz/jambonz-feature-server/blob/main/lib/session/call-session.js#L603 missing the riva implimentation

**Comment by davehorton** [comment]
fixec
