### ISSUE TITLE
Feature: more advanced queues

### ISSUE THREAD

**Issue by avoylenko** [jambonz/jambonz-feature-server#357]
At this moment jambonz implemented FIFO queues where the [enqueue](https://github.com/jambonz/jambonz-feature-server/blob/main/lib/tasks/enqueue.js) tasks pushes call into the queue and the [dequeue](https://github.com/jambonz/jambonz-feature-server/blob/main/lib/tasks/dequeue.js) task gets the calls from the queue. 

We need to implement additional setting called priority for the enqueue task, the priority setting will prioritise or even set a lower priority for an inserted call. 

Also it would be very useful to implement ability get a call based on index/call_id from the queue using the dequeue task.

**Comment by michaelschattgen** [comment]
We would like to see priorities added as well as it would improve our call flows and simplicity of our node-red flows.

To add (as I think this is a good place for other queuing improvements); we would like to have the ability to request an API to manipulate and retrieve the current states of the different available queues. This way we can easily estimate wait times or know how many callers are in the queue without having to manually keep track of all the calls.

**Comment by xquanluu** [comment]
start working on this.

**Comment by davehorton** [comment]
@xquanluu before writing much code, can you suggest the changes to the enqueue/deque verb that would be necessary?  Please make sure also that any changes are backwards compatible; i.e. it should be possibly to contine enqueuing and dequeing calls without priority if that is desired

**Comment by xquanluu** [comment]
Di @davehorton 
Here is my solutions, to keep thing simple and respect legacy enqueue, dequeue, leave verbs

1/ **Enqueue**
-- priority: 0 - 99, 0 is highest priority, 99 is lowest prioirty/non priority
2/ **Dequeue**
-- call_sid: the call_sid that we want to take from the queue. action failed if cannot find the call_sid in the queue.

Implementation:
Based on Redis Sorted set:
**pushBack:** use priority and timestamp to do queueing, as if items in the sorted set have same priority, the items are sorted lexicographically.
ZADD tasks 99 16300000000:url1
ZADD tasks 0 163000000001:url2
ZADD tasks 0 163000000002:url3
ZADD tasks 1 163000000003:url4

**popFront(call_sid = null)**: 
if call_sid === null
**ZRANGE tasks 0 0**: return 163000000001:url2
ZREM 163000000001:url2
**ZRANGE tasks 0 0**: return 163000000002:url3
ZREM 163000000002:url3
**ZRANGE tasks 0 0**: reutrn 163000000003:url4
ZREM 163000000003:url4
**ZRANGE tasks 0 0**: return 16300000000:url1
ZREM 163000000000:url1

after successfully fetched the item, use to release the item in queue

if call_sid 
ZSCAN tasks 0 MATCH *url1: return 1 16300000000:url1
ZREM 16300000000:url1

The changes is simple as that. Please let me know if you have any comments.

**Comment by davehorton** [comment]
I would prefer to not put an upper limit on the priority value, and have the default value be 999.  The only requirement is that if provided it must be a non-negative integer value.

So in terms of the changes to webhook verbs, does this look good?

**enqueue**
Currently defined as [this](https://github.com/jambonz/verb-specifications/blob/8ccb13f9625f3cc1c168db3d524648498291d9f4/specs.json#L98)

Will now have an additional (optional) `priority` property
```json
    "properties": {
      "id": "string",
      "name": "string",
      "priority": "number",
      "actionHook": "object|string",
      "waitHook": "object|string",
      "_": "object"
    }
```
If `priority` is not specified it will default to 999.  If specified, it must be a non-negative integer (and can be greater than 999), otherwise it will be ignored (warning logged by feature-server).

**dequeue**
Currently defined as [this](https://github.com/jambonz/verb-specifications/blob/8ccb13f9625f3cc1c168db3d524648498291d9f4/specs.json#L86)
Will now have an additional (optional) `callSid` property:
```json
    "properties": {
      "id": "string",
      "name": "string",
      "callSid": "string",
      "actionHook": "object|string",
      "timeout": "number",
      "beep": "boolean"
    },
```
If `callSid` is provided `dequeue` will dequeue that specific call, if it exists in the queue, returning an error otherwise.  If not provided, dequeue will dequeue the lowest priority call in the queue and if multiple calls have the same lowest priority they will be dequeued in FIFO order.

Does all that sound right?

**Comment by davehorton** [comment]
I would like to approach this development in a more collaborative way than usual.  Normally, we take requirements, implement and then release.  However, since you guys @avoylenko and @michaelschattgen are driving the requirements, I would appreciate it if you could help us test the development branch for these changes prior to release, in order to make sure they are satisfying your requirements.  Do you have the ability to create a test environment on which help us test this feature?

**Comment by michaelschattgen** [comment]
>Do you have the ability to create a test environment on which help us test this feature?

Yes, sounds good! I am able to test this on a a test environment prior to release.

**Comment by avoylenko** [comment]
@davehorton i will help with testing as well. Also, I might need to tune `/Accounts/{AccountSid}/Queue` endpoint to get actual queues state after this change.

**Comment by xquanluu** [comment]
Hi @avoylenko @michaelschattgen 

I just opened new PR above #362, it's great if you spen sometime to deploy this and test with priority and callSid as mentioned above.

Please let's me know if you need any thing from me to finish this test.

**Comment by davehorton** [comment]
@xquanluu can you give @avoylenko and @michaelschattgen  instructions on how to build a test environment?  I'm assuming that if they start with a jambonz-mini at version 0.8.3 they just have to checkout your branch (and build it) but is it just this repo or do any others need to be updated?

**Comment by xquanluu** [comment]
Hi @davehorton you are correct, that's all, they just need to:
1. cd /path/to/jambonz-feature-server
2. git pull && git checkout feat/advanced_queue
3. npm i
4. pm2 restart all

**Comment by davehorton** [comment]
ok step 2 might be `git fetch && git checkout feat/advanced_queue` I think ?

ok @avoylenko and @michaelschattgen  would love for you to test and report your findings and comments

**Comment by avoylenko** [comment]
@xquanluu it was faster than i thought, it seems like [realtimedb-helpers](https://github.com/jambonz/realtimedb-helpers) must be tuned as well, specifically the `lengthOfList` and the `getListPosition` methods to support the new data structure.

I observe the below errors when I put a call into a queue:

`{"level":50,"time":1685467409975,"pid":665891,"hostname":"ip-10-0-150-157","err":{"type":"ReplyError","message":"WRONGTYPE Operation against a key holding the wrong kind of value","stack":"ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value\n    at parseError (/home/admin/apps/jambonz-feature-server/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/home/admin/apps/jambonz-feature-server/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"llen","args":["queue:9351f46a-678c-43f5-b8a6-d4eb58d131af:queue-75ac9410-79b1-123c-f0bc-06d9a3589499"]}},"msg":"length: Error getting length list queue:9351f46a-678c-43f5-b8a6-d4eb58d131af:queue-75ac9410-79b1-123c-f0bc-06d9a3589499"}
{"level":50,"time":1685467409975,"pid":665891,"hostname":"ip-10-0-150-157","err":{"type":"ReplyError","message":"WRONGTYPE Operation against a key holding the wrong kind of value","stack":"ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value\n    at parseError (/home/admin/apps/jambonz-feature-server/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/home/admin/apps/jambonz-feature-server/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"lrange","args":["queue:9351f46a-678c-43f5-b8a6-d4eb58d131af:queue-75ac9410-79b1-123c-f0bc-06d9a3589499","0","-1"]}},"msg":"length: Error getting position of item http://10.0.150.157:3000/v1/enqueue/f439ab07-c276-40fe-b787-9ea3a07b155d list queue:9351f46a-678c-43f5-b8a6-d4eb58d131af:queue-75ac9410-79b1-123c-f0bc-06d9a3589499"}`

**Comment by xquanluu** [comment]
Thanks a lot @avoylenko, it's helping me a lot. Let me fix this and test from my site again. I was thinking that the queue is simply save and fetch, there are other process that do much more than I'm expecting.

**Comment by xquanluu** [comment]
Hi @davehorton 
I have created new PR for realtimeDB to get the position of element in sorted set: https://github.com/jambonz/realtimedb-helpers/pull/45

I also added 2 testcases:
1/ enqueue and dequeue work and briged 2 legs
2/ enqueue and waithook return leave.

Testcase here: https://github.com/jambonz/jambonz-feature-server/pull/362/files#diff-3ce3ea1638c3d61e78b49f371540fe185af04cbf19956889ac8bc5a05820aa72

I also changed and pushed new iamge for jambonz/webhook-test-scaffold to support waithook.

**Comment by davehorton** [comment]
@xquanluu I have published your change in realtime-dbhelpers as 0.8.2

**Comment by xquanluu** [comment]
Thanks @davehorton 
@avoylenko @michaelschattgen could you please help me once again, it would be nice if you can give one more time.

I have tested by intergration testcase and it's working as my expectation, hope it work with you.

**Comment by xquanluu** [comment]
Hi @avoylenko it's so nice,

I have fixed the queue_position is always 0, it's because I put wrong pattern to find the element in the queue.

I have added callSid and callId to wait hook payload:

{
    queueSid: 'queue:bb845d4b-83a9-4cde-a6e9-50f3743bab3f:support1',
    queueTime: 0,
    queueSize: 1,
    queuePosition: 1,
    callSid: 'ee0f9ab8-916c-4995-98ef-be976c2b5d0f',
    callId: '1-1@172.38.0.10-1'
  }

**Comment by michaelschattgen** [comment]
Sorry for my delayed response and thanks for the work! I just updated the feature server to the advanced_queue branch and did some testing with our existing Node-RED queuing flow. As of now I can't find any issues with it and the queue_position seems to correctly reflect the priority. Dequeuing also seems to work perfectly without any problems. I will do some extended testing later today and I'll let you know if I run into any issues.

If you'd like I can update the Node-RED contrib library to contain the new 'priority' field in its Enqueue node.

**Comment by xquanluu** [comment]
yes sure @michaelschattgen , it really nice if you can create PR on node red lib to reflect:
1/ priority in enqueue
2/ callSid in dequeue

**Comment by avoylenko** [comment]
@xquanluu it seems the `queuePosition` is fixed, but a call with the highest priority still has a value of `0`. I suppose it should be `1`.

**Comment by xquanluu** [comment]
Hi @davehorton @avoylenko 
I'm not sure, what is legacy behavior? I wouuld respect the backword compatible

List index should be started at 0, is it right?
If later there is a request to dequeue at index, the `zrange <queue> <index> <index>` should work properly without any modification of index must minus 1

**Comment by avoylenko** [comment]
@xquanluu you are right, according to the docs on https://www.jambonz.org/docs/webhooks/enqueue/.

@davehorton Is there are a way to update the document there to reflect the new changes?

**Comment by xquanluu** [comment]
so nice, Can I say that the feature passed all your test?

**Comment by avoylenko** [comment]
@xquanluu everything works as expected. Just found that the account-level webhook for queue events (_Queue event webhook_ on the account page) still has invalid value for `length` property. Please check the `performQueueWebhook` method used by the `enqueue` task.

**Comment by xquanluu** [comment]
omg thanks a lot @avoylenko Fixed it now. can you try again please?

**Comment by avoylenko** [comment]
@xquanluu thanks, i see no issues with the latest build. Great work!

**Comment by davehorton** [comment]
Can you guys review the docs changes to [enqueue](https://next-static-site-8t6qpaj46-jambonz.vercel.app/docs/webhooks/enqueue/) before I publish them?  There were no needed changes for the `dequeue` docs, right?

**Comment by davehorton** [comment]
Sorry, there *were* changes to `deqeueue`.  Updated docs [here](https://next-static-site-96rkb8tza-jambonz.vercel.app/docs/webhooks/dequeue/)

**Comment by davehorton** [comment]
I've merged the branch to main.  Could you guys now pull the latest main and re-test with that to be sure all is working?

**Comment by davehorton** [comment]
Also, I would love to write up a blog post describing this new feature, and I wonder if either of you would help since you have created at least a test app that we could possibly show.  Would you be willing to write up a brief description of your test app and give me screenshots showing how it was built, integrates to jambonz, and works ?  I could then draft a blog post that you could review for accuracy?

**Comment by avoylenko** [comment]
> I've merged the branch to main. Could you guys now pull the latest main and re-test with that to be sure all is working?

I'm ready to test as soon as merge is done

**Comment by davehorton** [comment]
merge is done

**Comment by avoylenko** [comment]
> merge is done

i don't see the changes in the main branch

**Comment by davehorton** [comment]
merged now, can you test when you get a chance?

**Comment by avoylenko** [comment]
@davehorton looks good, just found another issue that i believe i missed during the testing. 

@xquanluu when a call is being dequeued, we receive a global queue webhook event about this activity and there we have invalid queue length.

The problem is here, I think `Math.max` function is no longer needed:
https://github.com/jambonz/jambonz-feature-server/blob/55935e3f357535a66d9e3a6318ed13b2749ca300/lib/tasks/enqueue.js#LL299C22-L299C22

**Comment by avoylenko** [comment]
@xquanluu all good now

**Comment by xquanluu** [comment]
Thanks a lot @avoylenko 
I'm closing this issue, please help to open new issue whenever you face issue again.
