### ISSUE TITLE
feat: Customize Hold music

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#364]
The feature is needed to customize hold music , hold music can be replaced with experience flow as bot IVR 

current did not find any such feature exists

**Comment by davehorton** [comment]
can you give me an example app that illustrates the use of moh?

**Comment by davehorton** [comment]
the idea is to use a webhook in dial for moh, if provided then when we get invite on hold unbridge the two legs and execute webhook app on calling party leg, when we get invite off hold bridge the legs again

**Comment by davehorton** [comment]
@xquanluu can you verify that setting the hold-music channel variable is one possible way of changing the default hold music?  If so, it is probably the simplest/best solution

**Comment by xquanluu** [comment]
https://developer.signalwire.com/freeswitch/Channel-Variables-Catalog/hold_music_16352624/

i'm checking this posibility

**Comment by davehorton** [comment]
can this be closed @vdharashive ?
