### ISSUE TITLE
Feat: Transcribe to have continuousasr  functionality 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#378]
In long continuous stream its necessary to detect sentences to make sense rather than just getting phrases, it would be nice to have continuous asr feature with a timeout

**Comment by xquanluu** [comment]
Start working on this.

**Comment by vdharashive** [comment]
@xquanluu i have tested the pull request https://github.com/jambonz/jambonz-feature-server/pull/398

its working as expected , can this be merged in main stream branch
