### ISSUE TITLE
Bug: Outbound call sipURI Issue

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#380]
dial({"callerId": "14258427415",
"answerOnBridge": true,
"actionHook": "/agent-dial-confirm",
"target": [
{
"type": "sip",
"sipUri": "sip:918422999@3.221.228.119",
"trunk" : "SBC",

}
],
})

invite header  INVITE sip:8422999004@3.221.228.119 SIP/2.0 and to header To: <sip:8422999@23.21.52.56:5060> should have same destination IP address as invite header in this case 3.221.228.119 but in to header its taking the IP of Source host 

2023/06/18 12:26:00.119247 172.31.10.85:5060 -> 3.221.228.119:5060
INVITE sip:8422999004@3.221.228.119 SIP/2.0
Via: SIP/2.0/UDP 23.21.52.56;rport;branch=z9hG4bKarFSBcrBD94aB
Max-Forwards: 70
From: <sip:+16468789548@23.21.52.56:5060>;tag=y1027X9pc9a9r
To: <sip:8422999@23.21.52.56:5060>
Call-ID: 1fe62bdb-8876-123c-72be-0eb94b3c8831
CSeq: 68991788 INVITE
Contact: <sip:+16468789548@23.21.52.56:5060>
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, NOTIFY, UPDATE, PRACK
Content-Type: application/sdp
Content-Length: 495
X-Account-Sid: 140324ee-5665-40d0-9c5f-1d9b9ce3f750
X-CID: 7b740b28a73303c83cb2f50abdbafbd6@0.0.0.0
X-Voip-Carrier-Sid: 03deea1a-29e3-4ba0-a37b-4bec6e6cc992
X-Call-Sid: 78cf9844-8405-46ca-8b5e-ef47aa3e3054
P-Asserted-Identity: "+16468789548" <sip:+16468789548@si-X733W7X1-122>

v=0
o=FreeSWITCH 1687060568 1687060569 IN IP4 3.225.225.190
s=FreeSWITCH
c=IN IP4 3.225.225.190
t=0 0
m=audio 54124 RTP/AVP 0 8 102 9 101 103
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:103 telephone-event/48000
a=fmtp:103 0-16
a=sendrecv
a=rtcp:54125
a=ptime:20

**Comment by xquanluu** [comment]
Closing this as PR is merges
