### ISSUE TITLE
srf.locals.serviceUrl not updated on subsequent listeners

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#384]
https://github.com/jambonz/jambonz-feature-server/blob/62bc6b4bac06c655e0b7345e7f4772fc36da8605/lib/utils/http-listener.js#L9

When PM2 spins up more than one FS instance, the http-listener.js cycles through listening ports until it finds an unused one. It appears that the `srf.locals.serviceUrl` is not updated with the latest port. 

The api-server uses serviceUrl to send an updateCall to the FS express IP & Port however this fails intermittently due to incorrect serviceURL.

**Comment by davehorton** [comment]
@xquanluu is this still an issue or was it fixed with your recent commit?

**Comment by xquanluu** [comment]
Yes, this is already fixed.
