### ISSUE TITLE
It's possible to barge in using * even if barge-in is deactivated.

### ISSUE THREAD

**Issue by paulotelles** [jambonz/jambonz-feature-server#389]
I'm sending some configurations and even with barge-in disable I can always barge-in with * character:

`[
    {
      "config":{
        "bargeIn":{
          "enable":false,
          "actionHook":"voice",
          "dtmfBargein":false,
          "sticky":false
        },
        "recognizer":{
          "punctuation":true,
          "vad":{
            "enable":false
          },
          "vendor":"microsoft",
          "language":"en-US"
        }
      }
    },
    {
      "play":{
        "loop":1,
        "url":"https://www2.cs.uic.edu/~i101/SoundFiles/PinkPanther30.wav"
      }
    }
  ],`

**Comment by xquanluu** [comment]
Freeswitch log:

bc0e0efa-9742-47b0-9881-99f3cf6acbc1 2023-07-06 23:51:25.450895 [DEBUG] switch_rtp.c:8004 RTP RECV DTMF *:2080
bc0e0efa-9742-47b0-9881-99f3cf6acbc1 2023-07-06 23:51:25.450895 [INFO] switch_channel.c:522 RECV DTMF *:2080
bc0e0efa-9742-47b0-9881-99f3cf6acbc1 2023-07-06 23:51:25.450895 [DEBUG] mod_dptools.c:2376 Digit *
bc0e0efa-9742-47b0-9881-99f3cf6acbc1 2023-07-06 23:51:25.450895 [DEBUG] switch_ivr_play_say.c:1933 done playing file https://www2.cs.uic.edu/~i101/SoundFiles/PinkPanther30.wav
bc0e0efa-9742-47b0-9881-99f3cf6acbc1 2023-07-06 23:51:25.510899 [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@10.0.214.82:5070 Command Execute [depth=1] hangup()
bc0e0efa-9742-47b0-9881-99f3cf6acbc1 EXECUTE [depth=1] sofia/drachtio_mrf/nobody@10.0.214.82:5070 hangup()

**Comment by xquanluu** [comment]
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Modules/mod-dptools/6586776/

2.1 Play a file, and don't allow it to be interrupted
<action application="set" data="playback_terminators=none"/> 
<action application="playback" data="sounds/soundfile.wav"/>

The [playback_terminators](https://developer.signalwire.com/freeswitch/Channel-Variables-Catalog/playback_terminators_16353264#0-about) [channel variable](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Dialplan/Channel-Variables_16352493#about) is set to none to disable stopping the playback on [DTMF](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Introduction/Glossary_13173966#dtmf) input. (The default terminator is *.)

We have to update drachtio msrf

**Comment by xquanluu** [comment]
Please review the final changes in infrag:
https://github.com/jambonz/jambonz-infrastructure/pull/54

@paulotelles here is the quick fix. On freeswitch machine, please edit :
`/usr/local/freeswitch/conf/dialplan/mrf_dialplan.xml` to add this line `<action application="set" data="playback_terminators=none"/>`
