### ISSUE TITLE
Call Recording using SIPREC to be able to pass custom headers

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#395]

**Comment by xquanluu** [comment]
Start working on this

**Comment by vdharashive** [comment]
{
  "verb": "config",
  "record": {
    "action": "startCallRecording",
    "siprecServerURL": "sip:srs@recording.example.com"
  }
}
should be to pass header like 


{
  "verb": "config",
  "record": {
    "action": "startCallRecording",
    "siprecServerURL": "sip:srs@recording.example.com"
    "headers" : {
        "X-id" : "sfsfgd",
"X-Name" : "dddd"
}

  }
}
JSON

**Comment by vdharashive** [comment]
Thanks @xquanluu i have tested it
