### ISSUE TITLE
Voice audio stream using websocket or grpc an alternative to sip-rtp

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#397]

**Comment by davehorton** [comment]
can we list links to the public 3rd party docs here @vdharashive ?

**Comment by vdharashive** [comment]
https://support.talkdesk.com/hc/en-us/articles/9484798498587-Conversation-Orchestrator-Streaming-Bidirectional-Audio
https://developers.ringcentral.com/engage/voice/guide/workforce/call-streaming/getting-started
https://developer.genesys.cloud/devapps/audiohook/

**Comment by vdharashive** [comment]
Asterisk has component which does this 

https://wiki.asterisk.org/wiki/display/AST/AudioSocket

**Comment by vdharashive** [comment]
https://github.com/CyCoreSystems/audiosocket

**Comment by davehorton** [comment]
This is different.  jambonz already has the equivalent of that -- it is the 'listen' verb where you can receive an audio stream.

**Comment by vdharashive** [comment]
audiosocket in asterisk can receive stream from external WebSocket and also send the stream to socket 

the we this is executed need to be different 
 
External WebSocket make a request to Websocket Bridge , this bridge make an outbound call to jambonz using asterisk. once jambonz answer the call it sent to extension in asterisk on which audiosocket establish a connection to Webscoket bridge in which external Webscoket sends audiostream , Webscoket Bridge then  send and receive audiostream to audiosocket . 

This is something i have planned to implement , but i wanted to avoid using asterisk if can use jambonz to do the same
