### ISSUE TITLE
rest outdial does not work properly if a websocket app is

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#420]
To recreate:
- create a websocket based application
- do a rest outdial specifying that application_sid
Result: the commands are not executed, the rest dial verb hangs until far end hangs up

**Comment by xquanluu** [comment]
Hi @davehorton 
I tried to reproduce the issue on jambonz.one but cannot reproduce it, here is log file
[log.txt](https://github.com/jambonz/jambonz-feature-server/files/12286471/log.txt)
