### ISSUE TITLE
feat: Fast speech-to-text recognition

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#448]
For some languages, the speech-to-text engine requires a longer time to decide on 'end of single utterance' (this can result in a poor user experience).

If the fast speech-to-text recognition workaround is enabled, will trigger a recognition event after a specified time after the last hypothesis.

https://techdocs.audiocodes.com/voice-ai-connect/#VAIG_Combined/speech_customization.htm#Fast20speech-to-text20recognition

**Comment by davehorton** [comment]
@xquanluu please start with a proposal for the changes to the verb-specifications

**Comment by davehorton** [comment]
merged
