### ISSUE TITLE
Bug: Call to webrtc clients fails,  if inbound call receive on another sip sbc server 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#450]
if there are two SBC-SIP servers, WERTC is enabled on both , Client is connected SBC-SIP1 over webrtc. if incoming call comes to SBC-SIP2 and when sbc-sip2 server try to reach webrtc client then there is divert request sent but call does not reach to webrtc client which is connected to sbc-spi1

**Comment by davehorton** [comment]
logs needed from both servers
