### ISSUE TITLE
Handling bot delay

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#451]
There can be the configuration of waiting experience messages to be played if the response from the bot/websocket is not received it threshold value. it should start playing messages randomly from the given array. if there any message received from bot the it can queue to execute after the completion of current message playing. queuing can be controlled by the configuration of the waiting experience setting

**Comment by vdharashive** [comment]
eg : 

"botdelay": {
      "enable": true,
       "interrupt" : true
       say/play :{
		["Please wait we are checking your request","Sorry it taking time"]       
       
       }
      
      }

**Comment by vdharashive** [comment]
refer 
https://techdocs.audiocodes.com/voice-ai-connect/#VAIG_Combined/handle-bot-delay.htm?Highlight=bot%20delay

**Comment by xquanluu** [comment]
design doc: 
https://docs.google.com/document/d/12EyzxBsIX5c4ET9111AOwLf4xPDvlyRZH1V6q-TQDdM/edit?usp=sharing

**Comment by davehorton** [comment]
@EgleHelms @Catharsis68 can you review and comment on the above design doc?

**Comment by davehorton** [comment]
@xquanluu @vdharashive we need some docs on how this feature works before we merge the PR.  Can you add a full description here with an example?

**Comment by xquanluu** [comment]
```
session
      .pause({length: 1.5})
      .gather({
        actionHook: '/gather/action',
        input: ['speech', 'digits'],
        timeout: 59,
        minDigits: 1,
        numDigits: 12,
        interDigitTimeout: 2,
        bargein: true,
        say: {
          text: 'Would you be willing to spend a few minutes with us about your call on 2023-10-18 '
        },
        recognizer: {
          vendor: 'default',
          language: 'default'
        },
        actionHookDelayAction: {
          enabled: true,
          noResponseTimeout: 4,
          noResponseGiveUpTimeout: 20,
          retries: 6,
          actions: [
            {
              verb: 'say',
              text: 'hi there this is bot no input test'
            },
            {
              verb: 'play',
              url: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3'
            }
          ]
        }
      })
      .send();
```

If verb:hook event from gather is sent and there is no response from http server or there is only ack without verbs from ws server. After 4 seconds, action Say verb will be executed. When Say verb is finished, after another 4 seconds, Play verb will be executed, the loop keep going.

If After 20 seconds and there is no response from application, the call will be hangup.
