### ISSUE TITLE
Wrong validation of hints leads to problem with gather (barge in)

### ISSUE THREAD

**Issue by paulotelles** [jambonz/jambonz-feature-server#456]
Barge in does not work when there is no hints using microsoft. When trying to barge in the gather is not starting because of a validation error on feature server.

That's related to a wrong validation of hints on feature server

...(rOpts.hints.length > 0 && typeof rOpts.hints[0] === 'string' &&
          {AZURE_SPEECH_HINTS: rOpts.hints.map((h) => h.trim()).join(',')}),
        ...(rOpts.hints.length > 0 && typeof rOpts.hints[0] === 'object' &&
When there is no hints, there is no length so it throws an error and the gather is not started.

call_sid: bc4aeaaa-c4c2-418f-9fe8-b74885c5284e

**Comment by davehorton** [comment]
By the way, when you mentioned that there was a validation error because there were no hints that was not true.  There were no errors at all in the log for this call.
