### ISSUE TITLE
PAID is included in B Leg Indiscriminately if present in A Leg

### ISSUE THREAD

**Issue by ajukes** [jambonz/jambonz-feature-server#459]
Within app, if the PAID header is not overridden within dial or target, the A-Leg PAID is included in B Leg. This is fine for trusted networks but majority of times for us, it is end user which should not see this header.

Quick search of code I can see the following line and believe this may be the issue

https://github.com/jambonz/jambonz-feature-server/blob/a09605fc51099c847b67472e82e55e9cf6dfef55/lib/tasks/dial.js#L436

Suggest potentially an env variable to turn on/off default PAID header on B Leg?

**Comment by davehorton** [comment]
yes we could have an env to disable this (current behavior should be default)

**Comment by xquanluu** [comment]
closing this issue as PR is merged
