### ISSUE TITLE
calls between authenticated users in the same sip realm should work even without an application

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#489]
Say two users 'daveh' and 'hoan' have each successfully registered with the sip realm 'sip.jambonz.me'.  If either tries to dial the other, the call should be connected, even though neither has configured a default application to be used for sip devices.

Say daveh calls hoan.  The invite received by the feature server will include the information that this call is from a registered user, in the X-Authenticated-User header:
```
2023-10-18 09:07:48.227897 send 1751 bytes to udp/[10.0.35.194]:5070 at 09:07:48.227790:
INVITE sip:hoan@sip.jambonz.me SIP/2.0^M
Via: SIP/2.0/UDP 174.129.198.113;rport;branch=z9hG4bKc93jm05pX0vQH^M
Max-Forwards: 70^M
From: "500" <sip:daveh@174.129.198.113:5060>;tag=Ueej6yetNUFra^M
To: <sip:hoan@sip.jambonz.me>^M
Call-ID: a62d0a12-e838-123c-3c91-028d3aae2477^M
CSeq: 74256242 INVITE^M
Contact: <sip:10.0.35.194:5060>^M
User-Agent: JsSIP 3.10.0^M
Allow: INVITE, ACK, CANCEL, BYE, UPDATE, MESSAGE, OPTIONS, REFER, INFO, NOTIFY^M
Supported: timer, ice, replaces, outbound^M
Content-Type: application/sdp^M
Content-Length: 1040^M
X-Account-Sid: 9351f46a-678c-43f5-b8a6-d4eb58d131af^M
X-CID: 5641s4hsa27f5pdq5cpd^M
X-Forwarded-For: 107.115.5.130^M
X-Authenticated-User: daveh@sip.jambonz.me^M
X-Original-Number: hoan^M
```

The feature server should handle the invite by first doing what it currently does -- looking for an application for device calls.  If none is found, before returning this:
```
2023-10-18 09:07:48.233032 send 345 bytes to wss/[107.115.5.130]:31102 at 09:07:48.232952:
SIP/2.0 480 Temporarily Unavailable^M
Via: SIP/2.0/WSS pv0uuk3dp2vm.invalid;branch=z9hG4bK3479183;received=107.115.5.130;rport=31102^M
From: "500" <sip:daveh@sip.jambonz.me>;tag=fur5colm45^M
To: <sip:hoan@sip.jambonz.me>;tag=vQ7a8SZXj45ap^M
Call-ID: 5641s4hsa27f5pdq5cpd^M
CSeq: 8264 INVITE^M
Content-Length: 0^M
X-Reason: no configured application^M
```
The feature server should do the following:
1. Separate the X-Authenticated-User into name and sip realm (e.g.: [daveh, sip.jambonz.me])
2. Construct a sip aor from the dialed user (hoan) and the sip realm, eg search for hoan@sip.jambonz.me
3. Check to see if the user is currently registered

If the user is not registered, then the INVITE shall be rejected as before.  But if the user is registered, the feature should construct a simple dial verb application that sends the call to that user.  The call status hook shall be a no-op object.  The call is thus completed to the dialed user.

This behavior is only for the scenario where no default application for sip devices has been configured.  If an application has been configured then that application should be used.

The other thing that needs to be done that is related to this, is to remove the warning in the webapp that forces people to have a default application configured before creating sip clients.

**Comment by davehorton** [comment]
also, there should probably be an env var that can **disable** this new behavior.  It would seem rare to want to disable it, but because there will be no call status hook, it could affect a customer's ability to track cdrs if they are using call status hooks for that (though they should really be using the influxdb time series database)

**Comment by davehorton** [comment]
This is working now, but I would like a further refinement.  Currently, we first check to see if there is a configured device calling application and only if one is not configured, do we then check to see if the call is to a registered user.  I would like to reverse this -- we should do things in the following order:
1.  If there is a X-Application-Sid header, use that application
2. If the call is to a registered user (and is coming from a registered device) place the call to that user
3. If there is a configured device calling application, route the call to that application
4. If all of the above fail, reject the call

**Comment by xquanluu** [comment]
There is an issue on sbc-inbound that it always add X-Application-Sid to device-call-application-sid and that make above logic at feature server will have no impact.

**Comment by davehorton** [comment]
OK but we can fix (change) that right?
