### ISSUE TITLE
Feature: enable use of Pause verb in outdial applications (call screening applications)

### ISSUE THREAD

**Issue by javibookline** [jambonz/jambonz-feature-server#521]
Currently only Taks with preconditions "Endpoint" or "StableCall" are allowed in an application used in the confirmHook of an outdial (e.g. for call screening purposes).

We wish to prompt the user with either a play/say verb to contextualize the incoming call, and more often than not we wish to wait a bit before the audio is played. We tried to create an application of the type: [pause, say, pause], also to give time to the user to hangup the call after the message has been played.

The tasks that currently can be used in these application types are (according to [this](https://github.com/search?q=repo%3Ajambonz%2Fjambonz-feature-server+%22this.preconditions+%3D+TaskPreconditions.%22&type=code) search)

- Dtmf
- Hangup
- Dialogflow
- Play
- Dequeue
- Say (as well as say-legacy)
- Sip-refer
- STT task
- Rasa
- Listen
- Lex
- SIP request
- Conference
- Enqueue

The feature request is to add Pause to the set of Tasks that can be used in outdial confirmHook applications.

**Comment by davehorton** [comment]
makes sense.

**Comment by davehorton** [comment]
merged
