### ISSUE TITLE
Feat: OnHoldMusic hook does not trigger when transcribe in dial is running

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#533]
can updatecall can be used to trigger moh hook

**Comment by davehorton** [comment]
The title makes it seem like this is a bug report, the description makes it sound like a new feature.  Please clarify with a full description, and logs if necessary

**Comment by vdharashive** [comment]
[onHoldHook.txt](https://github.com/jambonz/jambonz-feature-server/files/13360456/onHoldHook.txt)
Logs attached
