### ISSUE TITLE
Feature Request: elevenlabs options

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/jambonz-feature-server#541]
We'd have the requirement to be able to configure the TTS provider `elevenelabs` similar to other providers via an `elevenlabsOptions` object.

According to [elevenlabs docs](https://elevenlabs.io/docs/api-reference/text-to-speech-stream) we'd like the following properties:

- model_id
- voice_id
- optimize_streaming_latency
- voice_settings
  - similarity_boost
  - stability
  - style
  - use_speaker_boost

**Comment by davehorton** [comment]
@xquanluu is this still open?

**Comment by davehorton** [comment]
this also requires changes to webapp as well

**Comment by davehorton** [comment]
ok lets work this.  They specifically have a new model that is supposed to be faster - turbo v2.  We should support it and make it the default in the webapp

**Comment by xquanluu** [comment]
The feature is deployed to jambonz.me
