### ISSUE TITLE
REST outdial with amd and separate gather fails to collect speech

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#542]
If we do a REST outdial and trigger an app that does a gather (like the echo app) it works properly, **unless** the `amd` property is included in the REST payload.  In that case, amd works but the gather returns no speech even though the caller is talking

**Comment by vdharashive** [comment]
@davehorton we had noticed this issue

**Comment by davehorton** [comment]
fixed in https://github.com/jambonz/jambonz-feature-server/pull/543
