### ISSUE TITLE
Application with Elevenlabs TTS not working

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/jambonz-feature-server#544]
We've enabled yesterday Elevenlabs in our Webapp downstream. Besides the other issue that got already resolved ([webapp issue](https://github.com/jambonz/jambonz-webapp/issues/352)) we are still facing the issue, that applications with Elevenlabs as TTS are not audible at all.

Here are logs from a feature-server call and also from the connected application
 
[elevenlabs-app.json](https://github.com/jambonz/jambonz-feature-server/files/13427804/elevenlabs-app.json)
[feature-server-0-elevenlabs.log](https://github.com/jambonz/jambonz-feature-server/files/13427806/feature-server-0-elevenlabs.log)

 I tested the Elevenlabs integration also directly with an app created via `npx create-jambonz-app`
 The `hello-world` scenario.

I run the app locally with an ngrok tunnel.
 
When I do a test call to the app with Speech provider Google - it works
When i switch to elevenlabs - it is not. (Voice Adam - en)
 
The credentials are valid - see "status ok". In addition I was testing elevenlabs with custom-speech-example repo, there it was also working. So the credentials are not the problem.
 
![Screenshot from 2023-11-21 12-26-02](https://github.com/jambonz/jambonz-feature-server/assets/6165055/dd619bac-2277-4de9-a1cf-ac159d82732e)
![Screenshot from 2023-11-21 12-23-01](https://github.com/jambonz/jambonz-feature-server/assets/6165055/e6838678-e5ff-4566-a761-e8235c9d40c3)

**Comment by xquanluu** [comment]
Hi @Catharsis68 From feature server log, I don't see any say verb is executed, I only see your application did not ack to the verb:hook request. Can you please provide another log?

{"level":30,"time":1700558613446,"pid":1,"hostname":"feature-server-0","callId":"789c423d-02f2-123d-eb8e-0aa8112367f9","callSid":"3cfd19cd-c410-4c42-ad8d-9906b6d219dd","accountSid":"1a3d4a19-a1e9-483f-8616-f8921fb0b959","callingNumber":"+14054321392","calledNumber":"+441409335812","traceId":"b4cca355bcc97241c58a7d9bcb387164","err":"timeout from far end for msgid 1h2uGzvGnPaGhkQN1NjUxf","msg":"Error retrieving or parsing application: undefined"}
{"level":20,"time":1700558613446,"pid":1,"hostname":"feature-server-0","callId":"789c423d-02f2-123d-eb8e-0aa8112367f9","callSid":"3cfd19cd-c410-4c42-ad8d-9906b6d219dd","accountSid":"1a3d4a19-a1e9-483f-8616-f8921fb0b959","callingNumber":"+14054321392","calledNumber":"+441409335812","traceId":"b4cca355bcc97241c58a7d9bcb387164","msg":"WsRequestor:close closing socket"}

**Comment by xquanluu** [comment]
I was trying to reproduce this on my jambonz.me instance as well but elevenlabs audio play for my text

**Comment by Catharsis68** [comment]
I'm not able to provide any more logs, there are none as soon as I switch to Elevenlabs for TTS.
What is your Elevenlabs setup?
Which language, which voice?

The same on jambonz.me. Could you take a look at the logs there?

**Comment by xquanluu** [comment]
Hi @Catharsis68  Can you please try again on jambonz.me, and give me the call-sid here, as I use multiple voice with same model but still I can hear the audio.

**Comment by Catharsis68** [comment]
I did some more testing and realized that the TTS generation for Elevenlabs just takes incredibly long (up to 15 seconds) for the "hello-world" scenario, so I was hanging up beforehand. 

All voices I tested in the webapp jambonz.me were working. Just out of interest, does the TTS generation also take such long for you?

I will close the ticket.

**Comment by xquanluu** [comment]
Yes, it's huge amount of time to generate audio from 10 seconds or above. We need to cache this before using it. this is known issue with elevenlabs
