### ISSUE TITLE
Deepgram barge in does not happens after the 3rd Barge In in the same call.

### ISSUE THREAD

**Issue by paulotelles** [jambonz/jambonz-feature-server#545]
Whe using deepgram with multiple barge in, it does not work after the 3rd one, not recognizing anymore.

call_id: 69d04f86-03c1-123d-8d9e-028d3aae2477

**Comment by xquanluu** [comment]
Hi @paulotelles 

After 3rd one, the call hangup due to the application tell jambonz to do that:
110|jambonz-feature-server  | {"level":30,"time":1700722795907,"pid":3000407,"hostname":"ip-10-0-35-194","callId":"b0bb0ec5-0470-123d-8d9e-028d3aae2477","callSid":"c9f352e2-f2cd-4d3c-91e4-93d5c27a2101","accountSid":"9351f46a-678c-43f5-b8a6-d4eb58d131af","callingNumber":"xhoaluu","calledNumber":"app-fd0dad8d-a51d-425c-a6f8-7909e4625fea","traceId":"907da2d5f356bc1747844e4962ad4bac","command":"redirect","queueCommand":true,"data":[{"hangup":{"headers":{"X-Reason":"Bot ended the call"}}}],"msg":"CallSession:_onCommand - received command"}


Do you know why?

**Comment by paulotelles** [comment]
@xquanluu but during the say node that I want to barge in, I can hear all the text and cannot barge in, I provided to Dave a  recording about that and an endpoint for testing

**Comment by xquanluu** [comment]
Hi @paulotelles 
I think there is missunderstanding here, Say/Play verb will be barge in if they are nested inside gather verb. In the application you show me, you are using Say verb outside of gather verb.


`[
    {
        "say": {
            "text": "You will need to barge-in here in this long text, just to see if barge-in is still working after the Go To Node. You can barge-in with Voice or DTMF, please feel free to interrupt me with one of these options. As soon as you barge-in, this call will be ended. Thank you for your call, we were happy to help you.",
            "disableTtsCache": false
        }
    }
]`

The you use command to queue Gather:

`[
    {
        "gather": {
            "input": [
                "speech",
                "digits"
            ],
            "timeout": 10,
            "actionHook": "voice",
            "recognizer": {
                "punctuation": true,
                "vendor": "deepgram",
                "language": "en-US",
                "hints": [],
                "altLanguages": [],
                "vad": {
                    "enable": false
                }
            },
            "minDigits": 1,
            "maxDigits": 1
        }
    }
]`

**Comment by xquanluu** [comment]
Hi @paulotelles Please let me know if thing works for you now?

**Comment by paulotelles** [comment]
@xquanluu  yes I used a say without a gather, but the barge in (background gather) was active by that time, so I should be able to barge in right?

**Comment by xquanluu** [comment]
Hi @paulotelles I'm still not be able to reproduce the issue.

https://www.loom.com/share/e4281d1b742740d18a956c5080676d1e?sid=c589a8e5-976b-4cd1-be13-3e4a14407cee

In my video, I think you cannot hear the voice from the dialer, but the callflow stop at the 3rd time normallu.

**Comment by xquanluu** [comment]
Could you please try to use latest jambonz version?

**Comment by xquanluu** [comment]
I cannot reproduce on jambonz.me:
https://www.loom.com/share/80ef9de02c634367920eb1901ef0a22d?sid=13191b9e-7023-47b3-9d81-8ad13c82aa97

Could you please try to use latest jambonz
