### ISSUE TITLE
Add utility function to pre-fetch and cache speech credentials at start of call

### ISSUE THREAD

**Issue by davehorton** [jambonz/jambonz-feature-server#547]
We have speech vendors like Nuance and IBM where there is a two-step process to using STT: first we have to generate an authentication token, then we use the token to do STT.  An example is [here](https://github.com/jambonz/jambonz-feature-server/blob/9478f3a1b8f29c6a5fcf3d020e95437201c1bf8d/lib/tasks/stt-task.js#L79).  This could lengthen the amount of time it takes until we are streaming the audio to the service provider so it would be better to:
1. Cache the authentication token for a period of time in redis, so we dont regenerate it on every call
2. Pre-fetch (and if necessary, generate) any such tokens at the beginning of the session, before we actually use it.

With regard to the second point, I am suggesting that at the start of the call if the application default STT vendor is one that requires an auth token, we retrieve or generate the token at that time (ie immediately, before we do a gather), so that it is available.

Something we need to consider is that these auth tokens are, by their nature, temporary so they need to have an expiry in redis.  Also, if we retrieve one from redis and it is within, say, 60 seconds of expiring, it would probably be best to generate a new one so that we don't have a credential that starts as valid but goes invalid during the call

**Comment by xquanluu** [comment]
https://github.com/jambonz/speech-utils/blob/main/lib/get-ibm-access-token.js
https://github.com/jambonz/speech-utils/blob/main/lib/get-nuance-access-token.js

The ticket seem already implemented and being used in feature server. Or may be I'm missing something

**Comment by xquanluu** [comment]
Hi @davehorton do you have any comment for this?
