### ISSUE TITLE
Bug: after pause transcript , trancripts are still generating

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#573]
Blow log shows there is a restart on the transcript due to no audio , even after pause transcript start flowing after restart 

way to reproduce is before keep call on mute and then issue pause , transcript will start flowing

DEBUG [07:41:35.464] (402046): received command
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
    command: "transcribe:status"
    call_sid: "30a66491-ba17-4aec-9db6-ce010a75019e"
    queueCommand: true
    data: {
      "transcribe_status": "pause"
    }
INFO [07:41:35.464] (402046): CallSession:_onCommand - received command
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
    command: "transcribe:status"
    queueCommand: true
    data: {
      "transcribe_status": "pause"
    }
INFO [07:41:35.465] (402046): TaskTranscribe:updateTranscribe status pause
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
DEBUG [07:41:36.530] (402046): TaskTranscribe:_onNoAudio restarting transcription on channel 1
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
DEBUG [07:41:51.156] (402046): TaskTranscribe:_onTranscription - before normalization
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
    evt: {
      "Id": "e311e1b3a0b04da2860d13ee5651d81e",
      "RecognitionStatus": "Success",
      "Offset": 119000000,
      "Duration": 7600000,
      "Channel": 0,
      "DisplayText": "User speaking.",
      "NBest": [
        {
          "Confidence": 0.70157737,
          "Lexical": "user speaking",
          "ITN": "user speaking",
          "MaskedITN": "user speaking",
          "Display": "User speaking.",
          "Words": [
            {
              "Word": "user",
              "Offset": 119000000,
              "Duration": 2400000,
              "Confidence": 0.52826107
            },
            {
              "Word": "speaking",
              "Offset": 121400000,
              "Duration": 5200000,
              "Confidence": 0.87489367
            }
          ]
        },
        {
          "Confidence": 0.4258158,
          "Lexical": "users speaking",
          "ITN": "users speaking",
          "MaskedITN": "users speaking",
          "Display": "users speaking",
          "Words": [
            {
              "Word": "users",
              "Offset": 119000000,
              "Duration": 2800000,
              "Confidence": 0.0016060595
            },
            {
              "Word": "speaking",
              "Offset": 121800000,
              "Duration": 4800000,
              "Confidence": 0.85002553
            }
          ]
        },
        {
          "Confidence": 0,
          "Lexical": "",
          "ITN": "",
          "MaskedITN": "",
          "Display": ""
        }
      ]
    }
DEBUG [07:41:51.156] (402046): TaskTranscribe:_onTranscription
    callId: "a428d3bc-181b-123d-05a6-0eb94b3c8831"
    callSid: "3d8686d3-f57e-4ec9-b94e-ca73a31d4ca3"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+18448735673"
    calledNumber: "+12055339731"
    traceId: "c9374f9f0b64235d992edeb61bd17513"
    evt: {
      "language_code": "en-US",
      "channel_tag": 1,
      "is_final": true,
      "alternatives": [
        {
          "confidence": 0.70157737,
          "transcript": "User speaking."
        }
      ],
      "vendor": {
        "name": "microsoft",
        "evt": {
          "Id": "e311e1b3a0b04da2860d13ee5651d81e",
          "RecognitionStatus": "Success",
          "Offset": 119000000,
          "Duration": 7600000,
          "Channel": 0,
          "DisplayText": "User speaking.",
          "NBest": [
            {
              "Confidence": 0.70157737,
              "Lexical": "user speaking",
              "ITN": "user speaking",
              "MaskedITN": "user speaking",
              "Display": "User speaking.",
              "Words": [
                {
                  "Word": "user",
                  "Offset": 119000000,
                  "Duration": 2400000,
                  "Confidence": 0.52826107
                },
                {
                  "Word": "speaking",
                  "Offset": 121400000,
                  "Duration": 5200000,
                  "Confidence": 0.87489367
                }
              ]
            },
            {
              "Confidence": 0.4258158,
              "Lexical": "users speaking",
              "ITN": "users speaking",
              "MaskedITN": "users speaking",
              "Display": "users speaking",
              "Words": [
                {
                  "Word": "users",
                  "Offset": 119000000,
                  "Duration": 2800000,
                  "Confidence": 0.0016060595
                },
                {
                  "Word": "speaking",
                  "Offset": 121800000,
                  "Duration": 4800000,
                  "Confidence": 0.85002553
                }
              ]
            },
            {
              "Confidence": 0,
              "Lexical": "",
              "ITN": "",
              "MaskedITN": "",
              "Display": ""
            }
          ]
        }
      }
    }

**Comment by davehorton** [comment]
we should stop the transcription when paused, start again when resumed

**Comment by davehorton** [comment]
actually, it looks like the code does properly stop the transcription when we get a pause command.  The issue appears to be a sort of race condition, where we stop the transcription but then get a "no audio" event (1 sec later in the log above).  When we get "no audio" we automatically restart the transcription, which is wrong because we should be in the "paused" state.  

I think the solution is that we need to explicitly track when we are in the paused state, and just discard no audio events (probably transcripts too)

**Comment by davehorton** [comment]
@vdharashive can you test the PR associated with this?
