### ISSUE TITLE
Bug: Hangup is not sending custom headers

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#582]
Hangup verb with header is not sending source 
  data: [
      {
        "verb": "hangup",
        "headers": {
          "X-KoreReason": "TransferToAgent"
        }
      }
    ]

DEBUG [08:55:13.002] (1031584): received command
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
    command: "redirect"
    call_sid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    queueCommand: true
    data: [
      {
        "verb": "hangup",
        "headers": {
          "X-KoreReason": "TransferToAgent"
        }
      }
    ]
INFO [08:55:13.002] (1031584): CallSession:_onCommand - received command
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
    command: "redirect"
    queueCommand: true
    data: [
      {
        "verb": "hangup",
        "headers": {
          "X-KoreReason": "TransferToAgent"
        }
      }
    ]
INFO [08:55:13.003] (1031584): CallSession:_onCommand - updated task list
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
    tasks: "[say{text=I will need to ...},hangup]"
DEBUG [08:55:13.459] (1031584): Say:exec completed play file /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:bbc6f727c36ce50d2a4f69924df2d0dce77b69ad.r8
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:13.459] (1031584): CallSession:exec completed task #1:5: say
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:13.459] (1031584): CallSession:exec starting task #1:6: say
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:13.459] (1031584): Speech vendor: microsoft  selected
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:13.459] (1031584): TaskSay:exec
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
    vendor: "microsoft"
    language: "en-AU"
    voice: "en-AU-NatashaNeural"
DEBUG [08:55:13.463] (1031584): file /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:8a97628244a530029c5c91931d09f5832f272c97.r8, served from cache true
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:13.463] (1031584): Say:exec sending command to play file /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:8a97628244a530029c5c91931d09f5832f272c97.r8
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.310] (1031584): Say:exec completed play file /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:8a97628244a530029c5c91931d09f5832f272c97.r8
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:20.310] (1031584): CallSession:exec completed task #1:6: say
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:20.310] (1031584): CallSession:exec starting task #1:7: hangup
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.311] (1031584): CallSession: call terminated by jambonz
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.311] (1031584): hangup is being killed
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:20.311] (1031584): CallSession:exec completed task #1:7: hangup
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
INFO [08:55:20.311] (1031584): CallSession:exec all tasks complete
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.312] (1031584): WsRequestor:close closing socket
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.312] (1031584): WsRequestor:close closing socket
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.312] (1031584): WsRequestor:request websocket: sent (wss://uat-smartassist.kore.ai/korevg/bot?botid=st-3ed8d64d-41c2-51c8-aa01-dd9e64155544&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBJZCI6ImNzLTRlMjE3MDlmLTRlYTgtNTdkNy05NWFhLWFlYTBhMDEzZjU3ZiJ9.9ULA2izm6AYfs6e2TkDnmrZgfAt_quxbDnoo_WDsirI)
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
    obj: {
      "type": "call:status",
      "msgid": "mWHn93Dwm5Zi5weWAUzDDY",
      "call_sid": "3e8d2fa4-0a77-4433-a86f-0a594df11122",
      "data": {
        "call_sid": "3e8d2fa4-0a77-4433-a86f-0a594df11122",
        "direction": "inbound",
        "from": "anonymous",
        "to": "+16094546141",
        "call_id": "a6cdc8b0-2001-123d-3b94-0eb94b3c8831",
        "sip_status": 200,
        "sip_reason": "OK",
        "call_status": "completed",
        "account_sid": "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2",
        "trace_id": "fbe56db3396e3f010cbde79c73bcf68c",
        "application_sid": "14be1e32-28c6-4356-9e89-a0047323b9cb",
        "fs_sip_address": "172.31.10.207:5060",
        "originating_sip_ip": "50.19.121.248",
        "originating_sip_trunk_name": "SMARTASSISTUATTRUNK",
        "call_termination_by": "jambonz",
        "duration": 8,
        "customerData": {
          "userNoInputCounter": 1
        }
      },
      "b3": "fbe56db3396e3f010cbde79c73bcf68c-60445f1f42340ffe-1"
    }
DEBUG [08:55:20.312] (1031584): CallSession:_clearResources successfully deleted /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:bbc6f727c36ce50d2a4f69924df2d0dce77b69ad.r8
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"
DEBUG [08:55:20.312] (1031584): CallSession:_clearResources successfully deleted /tmp/tts-3e8d2fa4-0a77-4433-a86f-0a594df11122c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2:8a97628244a530029c5c91931d09f5832f272c97.r8
    callId: "a6cdc8b0-2001-123d-3b94-0eb94b3c8831"
    callSid: "3e8d2fa4-0a77-4433-a86f-0a594df11122"
    accountSid: "c8e2ffe2-e6d1-46a7-9a63-1a662bc0dfc2"
    callingNumber: "+16176754444"
    calledNumber: "+16094546141"
    traceId: "fbe56db3396e3f010cbde79c73bcf68c"

**Comment by davehorton** [comment]
I dont understand what you mean by "not sending source".  Also please include the SIP BYE that was sent

**Comment by vdharashive** [comment]
yes Bye did not had custom headers

**Comment by vdharashive** [comment]
Its working now
