### ISSUE TITLE
Bug: custom TTS cache not playing wav files

### ISSUE THREAD

**Issue by vasudevan-Kore** [jambonz/jambonz-feature-server#585]
In case of custom TTS vendor the TTS cached wav files are not being played. The request is routed to cache and the files are not being played. If we clear the cache the request is routed to the custom speech engine and it works.

**Comment by xquanluu** [comment]
Hi @vasudevan-Kore 

This issue is because your TTS custom endpoint return to jambonz wav file.

We are not currently support caching wav file. Please help to return mp3 file.
