### ISSUE TITLE
Feat: apply config synthesizer.options in say task

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/jambonz-feature-server#589]
## Feature Request

**Use Case:** 

We want to apply advanced elevenlabs synthesizer options on a "global" level for a whole call via config verb.

**Actual:**
It is possible to apply the elevenlabs options via say task. `synthesizer.options` are being used when calling `synthAudio`
    - with this approach, we'd need to define the options on every say task in our flow editor where we generate the say task payload

**Goal:**
We can send the same `synthesizer.options` at the beginning of a call via `config` task and if defined, they will be used for `synthAudio`. In the case the say task has it's own `synthesizer.options`, this should overwrite the "config" settings.

**Comment by xquanluu** [comment]
Hi @Catharsis68 I have tested this PR on jambonz.me, 

Please help to test on your system please

**Comment by xquanluu** [comment]
I close this ticket as I remember @Catharsis68  already provided the PR for this
