### ISSUE TITLE
speechSegmentationSilenceTimeoutMs giving error for azure 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#626]
{
  "level": 20,
  "time": 1706104111064,
  "pid": 1981,
  "hostname": "demo-xo-savg-mini-debain-1",
  "callId": "09f3230c-3562-123d-b988-0022486ecff0",
  "callSid": "0a4fb312-1942-4a59-ab7d-2d8320dcd719",
  "accountSid": "f0ea1022-97c9-4861-9996-3df07aa56f90",
  "callingNumber": "u-96cf7d8f-1c08-590a-b8f5-5ebba1b305b6",
  "calledNumber": "st-e0026bab-1ff3-5a93-8f30-51fa5cc8d974",
  "traceId": "05bef1b35882807aeda0f961f1f36a89",
  "command": "redirect",
  "call_sid": "0a4fb312-1942-4a59-ab7d-2d8320dcd719",
  "queueCommand": true,
  "data": [
    {
      "verb": "tag",
      "data": {
        "userNoInputCounter": 1,
        "retryCount": 3
      }
    },
    {
      "verb": "gather",
      "actionHook": "/actions/hooks",
      "input": [
        "digits",
        "speech"
      ],
      "interDigitTimeout": 2,
      "minDigits": 1,
      "finishOnKey": "*",
      "numDigits": 12,
      "bargein": false,
      "listenDuringPrompt": false,
      "timeout": 59,
      "recognizer": {
        "vendor": "microsoft",
        "asrTimeout": 1,
        "asrDtmfTerminationDigit": "#",
        "label": "microsoft_hp_en",
        "azureOptions": {
          "speechSegmentationSilenceTimeoutMs": 2
        }
      },
      "say": {
        "text": "What is the serial number of your HP product?"
      },
      "dtmfBargein": false
    }
  ],
  "msg": "received command"
}{

{
  "level": 20,
  "time": 1706104114085,
  "pid": 1981,
  "hostname": "demo-xo-savg-mini-debain-1",
  "callId": "09f3230c-3562-123d-b988-0022486ecff0",
  "callSid": "0a4fb312-1942-4a59-ab7d-2d8320dcd719",
  "accountSid": "f0ea1022-97c9-4861-9996-3df07aa56f90",
  "callingNumber": "u-96cf7d8f-1c08-590a-b8f5-5ebba1b305b6",
  "calledNumber": "st-e0026bab-1ff3-5a93-8f30-51fa5cc8d974",
  "traceId": "05bef1b35882807aeda0f961f1f36a89",
  "obj": {
    "type": "jambonz:error",
    "msgid": "vLRH4e5P9fBkH4ybHiF2sr",
    "call_sid": "0a4fb312-1942-4a59-ab7d-2d8320dcd719",
    "data": {
      "msg": "ASR error",
      "details": "Custom speech vendor microsoft error: Connection was closed by the remote host. Error code: 1007. Error details: Could not validate speech context. SessionId: b24c6eafb0a840b2a5c4caab5b1a5ed5",
      "verb": "gather"
    }
  },
  "msg": "WsRequestor:request websocket: sent (/error)"
}

**Comment by davehorton** [comment]
can we close this issue @vdharashive ?
