### ISSUE TITLE
Need support to able to start recording and dial method using lcc command using wssocket 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#642]
config verb recording and dial verb to be supported in wss command 

recording is needed to start recording on dail with transcribe verb , since its blocking function. also for conference dial verb using wss 

https://www.jambonz.org/docs/ws/command/

**Comment by davehorton** [comment]
I don't understand the request.  Since you are suggesting a change to the verb syntax, perhaps you can show some examples of what it would look like

**Comment by vdharashive** [comment]
@davehorton 

below command will have same flexibility as recording verb 

https://www.jambonz.org/docs/supporting-articles/siprec-client/

command: "config:record"
    queueCommand: true
    data: {
      "record": {
    "action": "startCallRecording",
    "siprecServerURL": "sip:srs@recording.example.com"
      }
      }

**Comment by vdharashive** [comment]
and for dial @xquanluu had done some work 


https://github.com/jambonz/jambonz-feature-server/pull/581
