### ISSUE TITLE
Bug: On asr Deepgram gather is not timing-out in timeout value

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#665]
options: {
      "actionHook": "/actions/hooks",
      "input": [
        "digits",
        "speech"
      ],
      "interDigitTimeout": 2,
      "minDigits": 1,
      "finishOnKey": "#",
      "numDigits": 12,
      "say": {
        "text": [
          "<speak>Do you know the flight number?</speak>"
        ]
      },
      "bargein": false,
      "listenDuringPrompt": false,
      "timeout": 3,
      "dtmfBargein": false,
      "recognizer": {
        "hints": [],
        "altLanguages": []
      }
    }

[34mDEBUG[39m [11:17:01.793] (1512577): [36mGather:_onTranscription for vendor deepgram[39m
    callId: "2dbdd148-4f3b-123d-529a-0affe5e7181b"
    callSid: "bb20dc43-7ec5-4e95-b38a-ff3686ff0fff"
    accountSid: "5c08914e-c863-4d11-aeb0-b7577c2552f6"
    callingNumber: "[+18448735673](tel:+18448735673)"
    calledNumber: "[+15638000463](tel:+15638000463)"
    traceId: "5426a197403fd7de21b5046b50783463"
    evt: {
      "type": "Results",
      "channel_index": [
        0,
        1
      ],
      "duration": 55.539936,
      "start": 0,
      "is_final": false,
      "speech_final": false,
      "channel": {
        "alternatives": [
          {
            "transcript": "2 1 6",
            "confidence": 0.9995616,
            "words": [
              {
                "word": "2",
                "start": 1.68,
                "end": 1.92,
                "confidence": 0.9918588
              },
              {
                "word": "1",
                "start": 1.92,
                "end": 2.24,
                "confidence": 0.9995616
              },
              {
                "word": "6",
                "start": 2.24,
                "end": 2.74,
                "confidence": 0.9998086
              }
            ]
          }
        ]
      },
      "metadata": {
        "request_id": "8801fcb4-2866-45bf-b13a-9b1d741e403a",
        "model_info": {
          "name": "2-phonecall-nova",
          "version": "2024-02-07.20824",
          "arch": "nova-2"
        },
        "model_uuid": "7e3b5bdf-85ed-4fd2-9f7a-7721bbcad97b"
      }
    }
    bugname: "gather_deepgram_transcribe"
    finished: "false"
[5:59](https://drachtio.slack.com/archives/C048CUJ7BJ7/p1708950576392959)
"duration": 55.539936,
[5:59](https://drachtio.slack.com/archives/C048CUJ7BJ7/p1708950588346579)
this is bug from jambonz
[5:59](https://drachtio.slack.com/archives/C048CUJ7BJ7/p1708950595161239)
and its reproducable

**Comment by vdharashive** [comment]
@davehorton @xquanluu 

"recognizer": {
          "vendor": "deepgram",
          "language": "en-US",
          "deepgramOptions": {
            "model": "nova-2-phonecall",
            "endpointing": 500,
            "numerals": true
          }
        }

if we set "numerals": true this issue is coming also this will come when smartformat : true
by setting no_delay : true then this will address the issue from deepgram side

https://developers.deepgram.com/docs/smart-format#results
Can you please expose this parameter

**Comment by davehorton** [comment]
actually if you enabled smart formatting then we automatically enable their no_delay property 
```
    if (var = switch_channel_get_variable(channel, "DEEPGRAM_SPEECH_ENABLE_SMART_FORMAT")) {
     oss <<  "&smart_format=true";
     oss <<  "&no_delay=true";
     /**
      * see: https://github.com/orgs/deepgram/discussions/384
      * 
      */
    }
```

**Comment by vdharashive** [comment]
thanks @davehorton

**Comment by davehorton** [comment]
However, we are **not** setting this when numeral=true, only when smart formatting=true.  Are Deepgram saying it is an issue in both cases?
