### ISSUE TITLE
Custom STT timeout after 10s

### ISSUE THREAD

**Issue by Vicfou-dev** [jambonz/jambonz-feature-server#672]
I'm using the 0.8.4 version of jambonz, 
I'm trying to add a custom STT but if I don't send back a final transcription before 10s the socket close with a 1006 error
I've also tried to send some false interim result each 3s to see if it was a reponse_timeout issue but it's don't seem to be that

Any idea ?

**Comment by davehorton** [comment]
I think you are running an old version of the freeswitch modules, this bug has been fixed

**Comment by davehorton** [comment]
I would suggest testing on jamboz.cloud which has latest,verify it is not an issue there then build with latest
