### ISSUE TITLE
Barge In does not flush more than one say node anymore.

### ISSUE THREAD

**Issue by paulotelles** [jambonz/jambonz-feature-server#676]
"call_id": "28598a95-5649-123d-8b9a-025325169175"
env: jambonz xyz

Whenever I have a barge in with three following say nodes I would expect the say nodes to be flushed as soon we barge in on the first say node. The behavior has changed and now for each say node I have to barge in again.

In this call we have a set session config enabling barge in and three say nodes.

If I bargein in the first say, the second one starts, I have to bargein again and on the third say it's not possible to barge in anymore.

Can you check please? This was not the behavior of barge in some months ago, something have changed.

**Comment by davehorton** [comment]
@paulotelles please note this fix
