### ISSUE TITLE
Play action doesn't work if dtmf keys are pressed during play

### ISSUE THREAD

**Issue by raheel-shahzad** [jambonz/jambonz-feature-server#683]
Play action is not performed if DTMF keys are pressed while playing the audio. The `call_sid` for the reference is `b42d4ed4-7f03-47f5-aefa-99e5bc2d3849`. The other issue is that if there is another verb after gather then it should move on to that verb after timeout but it submits to gather verb with empty digits. The `call_sid` for second issue is `53887c77-0cce-4bf6-8018-c82c202443c1 `

**Comment by davehorton** [comment]
looks like we started a gather, started playing the audio, then you pressed DTMF 1 after 7 seconds so we killed the audio since you had specified dtmfBargein.  Can you be more specific about what you feel was wrong?

```
[01:38:43.974] DEBUG (964880): Gather:exec
    callId: "6f24b5bb-5c46-123d-a2b6-0e9252b57157"
    callSid: "b42d4ed4-7f03-47f5-aefa-99e5bc2d3849"
    accountSid: "xxx-2dbc-4de9-a572-fdaa3c2e1e39"
    callingNumber: "Anonymous"
    calledNumber: "16474488190"
    traceId: "c7c58745a5228ad350eb12640e8287f6"
    options: {
      "actionHook": "https://xxx.org/calling-system/main-menu?link=aHR0cHM6Ly9zaGFzaWxsdW1pbmF0ZWQub3JnL2NhbGxpbmctc3lzdGVt",
      "input": [
        "digits"
      ],
      "dtmfBargein": true,
      "numDigits": 1,
      "finishOnKey": "9",
      "play": {
        "url": "https://d3mlxbcjhgghjjgo2.cloudfront.net/hotline_recordings/home_play.mp3"
      },
      "recognizer": {
        "hints": [],
        "altLanguages": []
      }
    }
[01:38:50.219] DEBUG (964880): TaskGather:_onDtmf
    dtmf: "1"
    duration: "2392"
    source: "RTP"
[01:38:50.219] DEBUG (964880): play is being killed
    traceId: "c7c58745a5228ad350eb12640e8287f6"
```

**Comment by raheel-shahzad** [comment]
I am talking about the section after the redirection. This first play is fine because it is inside gather (Gather with Play verb). After this redirection, there is a single say verb and then there is a single play verb. During this play verb, I have defined an actionHook for play but that doesn't respond on dtmf keys. In short, Gather with play or say verb works perfectly. But a play verb with actionHook doesn't call it on key press.

**Comment by davehorton** [comment]
I think you misunderstand the actionHook in the play verb.  It does not notify you of dtmf.  It only notifies when play completes.  During your play command we were not listening for dtmf - you would need to use the gather for that

**Comment by raheel-shahzad** [comment]
@davehorton There was also another issue. If there is another verb after gather then it should move on to that verb after timeout but it submits to gather verb with empty digits. The `call_sid` for second issue is `53887c77-0cce-4bf6-8018-c82c202443c1`
