### ISSUE TITLE
feat: Single session connection for microsoft for asr for a call

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#747]
Microsoft supports single-session connection for an entire call rather than connecting and disconnecting for each gather to be supported this will reduce latency of connecting each time

**Comment by davehorton** [comment]
@vdharashive please point us to or describe api that lets us tell microsoft we are pausing/resuming audio?  We need to mnake sure billing stops or else this feature doesnt make sense
