### ISSUE TITLE
Zero KB files in /tmp/tts-cache-files 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#760]
/tmp/tts-cache-files 
in folder there many zero KB files getting created this is causing lookup issues to load the folder , this will have issue in performance disk IO will increase  

-rw-rw-rw- 1 root daemon    0 May 19 02:34 a73ee942-b04b-4b17-858e-040e1a2a1610.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:35 6f25b9d5-7667-487d-a5fa-ddad00fed137.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:35 2a75e8ee-4aea-4743-a61d-3513d7bffce0.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:53 2f15e4eb-371c-4cef-8bee-3660e9a390b6.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:53 f1d9e8cf-f6df-4650-a3cb-7d8af14e11ab.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:56 c0a3a1f7-c158-4483-8259-e148ecc2b380.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:56 8467f393-f480-4d19-ae18-082f8564b93a.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:57 b5cdbab8-eca5-43e8-a910-b32aae3309b4.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:57 f888e9f1-369f-476c-ac1f-3df16648776a.r8
-rw-rw-rw- 1 root daemon    0 May 19 02:58 4904c355-7692-4ef8-8e1d-36b7fcca231e.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:11 3fe78ee9-04db-4d54-89b7-c9cfd2a86066.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:11 cc152957-13d7-44cf-8ec0-001feb7c3795.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:12 cd512bc2-18fe-482d-9e6e-9f7fcf7db5be.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:13 d985da3e-3e9a-4c90-97c5-b12e5b268065.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:13 9e5bfd1e-1fe2-478c-a290-e123c21fb1ad.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:20 5f3b4d8f-a67b-44de-95fd-866c9a70b1eb.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:20 1dbf7206-eb9a-48a9-acaa-fdd16b231704.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 a7beb905-4e47-4a33-82f9-fa326ab56794.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 1b4e70fe-3d0c-4960-b353-bf3fde6cdda6.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 82fe0c94-dff9-483d-a907-aa6f86196d94.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 c6099493-859e-485d-bc63-5f6d84a9bb22.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 a5937d8b-8cac-41f1-a425-76f58337f456.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 67a52d5c-ebf8-443e-9b24-631d8d340001.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 affde6ca-8768-4c20-ad4b-4ba4bda406f6.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 9a2ffcdc-1b64-44c0-9987-619b75b997d8.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:22 c1754f0b-8b60-4087-9142-33e11c1b21dc.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:23 1ca9e4cb-e68c-4641-af24-9294515ae6a9.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:23 0d135ffe-c5c4-4520-b2bb-ed9e9eeae1bd.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:23 ae361e14-ddf3-43ea-a32a-e9b6a41bf06d.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:24 574b77fa-0b13-4904-b7b8-887510475bc0.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:24 bef8f4a6-b4c0-4169-a11d-bb14db8d85ee.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:25 64d79ba7-b15c-4fe6-9046-437ed5201394.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:25 46479f0b-2c79-4b2d-b884-da5e08230d8d.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:25 ab682d72-d038-43b0-be32-4758ba5cbd4c.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:26 ecaa234c-04bf-44c3-b3a9-d0ea71d10447.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:26 3d577e1f-7f2c-483e-b3f3-399fd14d7fd0.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:28 8e887746-e7e2-4fe6-a526-7cdff84a1ca4.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:28 f71ed7fa-657f-4a64-8c52-a9d6b4ca4367.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:30 b0007bfd-ba1f-4eb3-9c37-fd3b7b54f5fd.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:30 6bb99e2e-a459-4a7c-8445-94950d3e0b99.r8
-rw-rw-rw- 1 root daemon    0 May 19 03:31 4c541ea8-4872-4127-9d6c-fd0b1a5d3a3c.r8

**Comment by davehorton** [comment]
This is likely because the caller hangup during a prompt and thus we did not completely render the audio.  We can look into recreating this and then see if we can immediately delete.  Also we need to look into why these files were not deleted when the session ended.

**Comment by xquanluu** [comment]
Hi @davehorton 

Feature server keep track tmp file when playback-start event is received with file name, so this issue is happening if caller hangup the call before this event happen.

I cannot reproduce the issue due to we need to hangup call as fast as before freeswitch send the event.

I will provide the fix and let you review if it's ok or not.

**Comment by xquanluu** [comment]
I can reproduce the issue.

We just need to provide wrong speech credential, that make synthesize request failed, speech_flush_tts will not clean up the tmp file.

**Comment by davehorton** [comment]
@vdharashive @xquanluu as a short term fix I think we should appluy a cron job that runs every 10 minutes and deletes zero-length files from this directory that are older than 5 minutes

**Comment by vdharashive** [comment]
@davehorton i have been deleting these
