### ISSUE TITLE
Bug: Microsoft stt fallback not woking for single connection imlimentation

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#774]
After implementation of single connection for Microsoft stt any fallback to stt is not working, mean fallback is not happening.

below logs are reverse 

}2024-06-0419: 33: 11.543{
  "level": 20,
  "time": 1717509791502,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "BackgroundTaskManager:stopAll"
}2024-06-0419: 33: 11.543{
  "level": 20,
  "time": 1717509791502,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "WsRequestor:close closing socket"
}2024-06-0419: 33: 11.543{
  "level": 20,
  "time": 1717509791502,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "WsRequestor:close closing socket"
}2024-06-0419: 33: 11.543{
  "level": 30,
  "time": 1717509791502,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "CallSession:exec all tasks complete"
}2024-06-0419: 33: 11.543{
  "level": 30,
  "time": 1717509791501,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "InboundCallSession: caller hung up"
}2024-06-0419: 32: 22.398{
  "level": 20,
  "time": 1717509742286,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "file /tmp/tts-2eec28e8-b1b9-4dc0-b107-b2947b59f9bbc9d26384-cead-4398-8a7c-4239c3b21689:r8:d2abaab814f8e865c146625b7a7f1a705b20d0f3.r8, served from cache true"
}2024-06-0419: 32: 22.398{
  "level": 20,
  "time": 1717509742285,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "obj": {
    "type": "jambonz:error",
    "msgid": "kLMErRqppQovAMdHXFTDMa",
    "call_sid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
    "data": {
      "msg": "ASR error",
      "details": "Invalid vendor microsoft, Error: Error: No speech-to-text service credentials for microsoft have been configured",
      "failover": "in progress",
      "verb": "gather"
    }
  },
  "msg": "WsRequestor:request websocket: sent (/error)"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742285,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "_awaitCommandsOrHangup - waiting..."
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742285,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "CallSession:exec completed task #1:3: gather"
}2024-06-0419: 32: 22.398{
  "level": 20,
  "time": 1717509742285,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "TaskSay:kill - killing audio"
}2024-06-0419: 32: 22.398{
  "level": 20,
  "time": 1717509742285,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "say is being killed"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "vendor": "microsoft",
  "language": "en-AU",
  "voice": "en-AU-NatashaNeural",
  "msg": "TaskSay:exec"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "tts: microsoft   "
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "stt: microsoft , label: microsoft_smartassist_dropdown  "
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "Failed to use primary STT provider, fallback to microsoft"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "ERROR stt using microsoft requested but creds not supplied"
}2024-06-0419: 32: 22.398{
  "level": 20,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "options": {
    "actionHook": "/actions/hooks",
    "input": [
      "digits",
      "speech"
    ],
    "interDigitTimeout": 2,
    "minDigits": 1,
    "finishOnKey": "#",
    "numDigits": 12,
    "say": {
      "text": [
        "welcome to ticket system let me know the which device you are using"
      ]
    },
    "bargein": false,
    "listenDuringPrompt": false,
    "timeout": 10,
    "dtmfBargein": false,
    "recognizer": {
      "hints": [
        
      ],
      "altLanguages": [
        
      ]
    }
  },
  "msg": "Gather:exec"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742284,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",
  "msg": "CallSession:exec starting task #1:3: gather"
}2024-06-0419: 32: 22.398{
  "level": 30,
  "time": 1717509742283,
  "pid": 1028713,
  "hostname": "ip-172-31-10-150",
  "callId": "e722d861-9d1d-123d-7d9a-0e2ecbcba261",
  "callSid": "2eec28e8-b1b9-4dc0-b107-b2947b59f9bb",
  "accountSid": "c9d26384-cead-4398-8a7c-4239c3b21689",
  "callingNumber": "u-4682b61f-651c-594c-8a39-f289371b223e",
  "calledNumber": "st-66fbcd15-0154-56b2-91d9-7a27da939fcd",
  "traceId": "31fc9477bb736c92afcda84abc3e8d51",

**Comment by davehorton** [comment]
please open a ticket in our support system with debug logs for freeswitch and feature server attached as files to the ticket and at debug level
