### ISSUE TITLE
The TTS of Outbound Call don't work.

### ISSUE THREAD

**Issue by Wayast** [jambonz/jambonz-feature-server#797]
I have configured sip trunk and Azure service in jambonz.cloud . The TTS speak for inbound  call is ok. But the outbound call will be hung up in 2 seconds after answered , and the alert show "speech credentials for microsoft have not been provisioned". 

Below is the payload for create call api:
{
    "call_hook": "https://public-apps.jambonz.cloud/hello-world",
    "call_status_hook":"https://public-apps.jambonz.cloud/call-status",
    "from": "38881001",
    "to": {
        "type": "phone",
        "number": "279991001"
    },
    "speech_synthesis_vendor": "microsoft",
    "speech_synthesis_language": "en-US",
    "speech_synthesis_voice": "en-US-AmberNeural",
    "speech_recognizer_vendor": "microsoft",
    "speech_recognizer_language": "en-US"
}

The inbound call application with same webhook and tts configuration is ok.

**Comment by davehorton** [comment]
please be sure that when you created your microsoft speech credential you did not add a label.

**Comment by Wayast** [comment]
Hi,Dave
      Thanks so much for your great support.Following your guide, I add second microsoft speech without label  now the TTS of outbound call is ok now.

Regards,

Wayast
________________________________
发件人: Dave Horton ***@***.***>
发送时间: 2024年7月4日 0:59
收件人: jambonz/jambonz-feature-server ***@***.***>
抄送: Wayast ***@***.***>; Author ***@***.***>
主题: Re: [jambonz/jambonz-feature-server] The TTS of Outbound Call don't work. (Issue #797)


please be sure that when you created your microsoft speech credential you did not add a label.
