### ISSUE TITLE
The Say node in node-red don't speak out {{msg.transcript}} 

### ISSUE THREAD

**Issue by Wayast** [jambonz/jambonz-feature-server#798]
It seems the Say node in node-red can not parsing the variable. I have tried use {{msg.transcript}} or ${msg.transcript} in the Text of Say node, but the content of {msg.transcript} would not be speak out. From the debug output, the {msg.transcript} have values.

@
![node-red-tts01](https://github.com/jambonz/jambonz-feature-server/assets/172966441/2d809a7a-ef23-4cf1-a35f-be2f9d045aa1)

**Comment by avoylenko** [comment]
First of all this is a wrong project to report bugs related to node-red. You supported to use `{{transcript}}` to get the data of to msg object.

**Comment by Wayast** [comment]
I sorry for choosing a wrong project to report bugs related to node-red!  Just test it, the {{transcript}}  is ok !
