### ISSUE TITLE
Introduce minConfidence property for gather verb

### ISSUE THREAD

**Issue by rammohanyadavalli** [jambonz/jambonz-feature-server#807]
The requirement is to return transcripts whose confidence levels are greater than or equal to the minConfidence property specified in the gather verb

**Comment by davehorton** [comment]
on hold pending further review of this features

**Comment by vdharashive** [comment]
gather notification should happen as "timeout" if confidence level is below its configured value and move to next verb

**Comment by vdharashive** [comment]
@davehorton can you review this feature cc @rammohan-kore
