### ISSUE TITLE
feat: say to support stream support

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#816]
llm modal stream continuous text , say is executed in sequence manner in jambonz, due to which there is lag created between two say command , hence ether say can execute multiple command parallel and generate tts audio file so that it would play in same sequence in which it has received .

**Comment by davehorton** [comment]
@vdharashive as a first try, please set the environment variable JAMBONES_EAGERLY_PRE_CACHE_AUDIO=1 and see if that helps

**Comment by vdharashive** [comment]
@davehorton could you help me to understand JAMBONES_EAGERLY_PRE_CACHE_AUDIO how this works to generate audio cache? , does it generate audio files of all pending say command from queue

**Comment by davehorton** [comment]
With this env var set, if we receive one or more say commands while there are other commands already queued, we will generate the audio and store that in redis so that when this latest say command is ready to be executed the audio should already be generated and cached locally

**Comment by vdharashive** [comment]
@davehorton say has renderForCaching parameter how does this work ? Is that I need to send two time say one for generating just audio cache and the other say for playing the say in its sequence without renderForCaching

**Comment by davehorton** [comment]
it is an environment variable.  simply set JAMBONES_EAGERLY_PRE_CACHE_AUDIO=1 for the feature-server process to enable this feature
