### ISSUE TITLE
Bug: Performance degradation on channel of User call after Kick from Conference 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#850]
we noticed significant latency in audio  played using say or gather verb , cracking sound after kicking user from conference and ending conference , also speech detection and dtmf detection has latency and timeout , this is reproducible scenario

**Comment by davehorton** [comment]
hmm, would it be possible to create simple app that reproduces this?

**Comment by vdharashive** [comment]
@xquanluu if you need any help please let me know

**Comment by xquanluu** [comment]
Close this issue as PR is merged:
https://github.com/jambonz/jambonz-feature-server/pull/878
