### ISSUE TITLE
Update the engine list for synthesizer spec

### ISSUE THREAD

**Issue by rammohan-kore** [jambonz/jambonz-feature-server#859]
We need to add generative and long-form to the existing list of enums for engine under synthesizer

**Comment by vdharashive** [comment]
https://docs.aws.amazon.com/polly/latest/dg/available-voices.html

**Comment by davehorton** [comment]
where is the PR for this issue?  I dont see a feature server PR

**Comment by rammohan-kore** [comment]
> where is the PR for this issue? I dont see a feature server PR

creating the feature-server PR, i was waiting for publish for verb-specs
