### ISSUE TITLE
Playht and elevenlab to pass model name using synthesizer verb

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#894]
Synthizer verb does not support model to be changed for playht and elevenlab, currently it's taking setting from applications configuration

**Comment by vdharashive** [comment]
Need to review also deepgram

**Comment by xquanluu** [comment]
as Jambonz webapp application synthesizer and recognizer have to be able to get list of available languages and voices, model is required to get them.

I'm creating a PR that allow to change model by synthesizer/recognizer from verb.
