### ISSUE TITLE
Playht and elevenlab voice quality 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#895]
There is difference in voice quality if on direct streaming vs  cache audio , this gives bad experience since voice pitch is changing

**Comment by davehorton** [comment]
is this recreatable?  it seems pretty strange, can you gather recordings to illustrate

**Comment by vdharashive** [comment]
@davehorton @xquanluu  Uploaded the recording in fd

**Comment by vdharashive** [comment]
Due to this we had to disable caching and we are reaching rate limit of playht
