### ISSUE TITLE
Implement standard Trace Context Propagation for action hook http requests

### ISSUE THREAD

**Issue by juansalvatella** [jambonz/jambonz-feature-server#90]
To enable linking traces between jambonz and external services, it is necessary to propagate trace context between services. I've seen that you've added a "TraceId" field on the payload when communicating with other services via action hooks over HTTP but it would be great to implement a Trace Context Propagation standard such as the standard W3 (https://w3c.github.io/trace-context/) or B3 from OpenZipkin (https://github.com/openzipkin/b3-propagation).

### More info here:
- https://opentelemetry.lightstep.com/core-concepts/context-propagation/
- https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-core#built-in-propagators
- https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/propagators

**Comment by davehorton** [comment]
yes, I need to understand this better.  Right now, I have implemented tracing in jambonz-feature-server and the trace context is not propagated anywhere.  What I would like to do is to implement tracing in sbc-inbound and propagate that context to jambonz-feature-server via a custom SIP header.  ATM I don't know how to do that -- I think my main problem is that I dont lknow how to receive / ingest trace context in the jambonz-feature-server side.  Any pointers you have on that will be useful

**Comment by davehorton** [comment]
a new header 'b3' is now included in all http requests (and a 'b3' property if ws is used)
