### ISSUE TITLE
Bugs: Google Transcribe issue when call is on hold and longer call more then 305 sec

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#919]
Transcribe needs to continue by restarting session with google if following two error are received when call is kept on hold for more then 10 sec or single session is running for 305 sec

1. Custom speech vendor google error: Exceeded maximum allowed stream duration of 305 seconds.
2. Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.

**Comment by davehorton** [comment]
do you mean specifically the 'transcribe' verb (versus the 'gather')?
