### ISSUE TITLE
Enhancement: opus codec transcoding at rtpengine for both inbound outbound call

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#938]
Currently calls going to webrtc client is using pcmu codecs since freeswitch is setting priority pcum as high 

For outbound call from jambomz to webrtc client jambonz send pcmu and webrtc client is acknowledge with opus in this case one leg of call using opus and other pcmu rather it should use opus based on client negotiations 

Similarly is case for inbound 

It would be good feature to have both inbound and outbound call rtpengine can manage opus for webrtc client and internally pcmu with freeswitch 

So rtpengine needs to have transcoding enables

Inbound call opus to pcmu 
Outbound call pcmu to opus

**Comment by xquanluu** [comment]
```
aae0e7b7-22e6-4e2e-a64d-07b8c440247c 2024-10-17 08:49:06.378160 0.00% [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@10.0.204.168:5070 Command Execute [depth=1] playback(/tmp/tts-f42089cf-91f3-4a74-9587-4eea2cbdcc18dc39416d-35c1-423e-9dc2-257d24390651:r8:4d7376193c098704213ce548a9cec1dd1c76a635.r8)
aae0e7b7-22e6-4e2e-a64d-07b8c440247c EXECUTE [depth=1] sofia/drachtio_mrf/nobody@10.0.204.168:5070 playback(/tmp/tts-f42089cf-91f3-4a74-9587-4eea2cbdcc18dc39416d-35c1-423e-9dc2-257d24390651:r8:4d7376193c098704213ce548a9cec1dd1c76a635.r8)
2024-10-17 08:49:06.378160 0.00% [DEBUG] switch_core_file.c:444 File /tmp/tts-f42089cf-91f3-4a74-9587-4eea2cbdcc18dc39416d-35c1-423e-9dc2-257d24390651:r8:4d7376193c098704213ce548a9cec1dd1c76a635.r8 sample rate 8000 doesn't match requested rate 48000
```

**Comment by vdharashive** [comment]
@davehorton as we had discussed rtpengine will transcode opus to pcmu for inbound and also pcmu to opus for outbound if client has opus as it's priority,  between rtpengine and freeswitch the codec will be pcmu
