### ISSUE TITLE
Update of optimalGoogleModels 

### ISSUE THREAD

**Issue by rammohan-y** [jambonz/jambonz-feature-server#942]
We need an update to the optimalGoogleModels in transcription-utils for es-DO, es-MX, en-AU, en-GB, en-NZ  and en-IN if model is not specified in gather, transcribe recognizer configuration

es-DO = default
es-MX = default
en-AU = telephony
en-GB = telephony
en-NZ  = telephony

**Comment by vdharashive** [comment]
https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages
