### ISSUE TITLE
Server cannot be reached after installing SSL...

### ISSUE THREAD

**Issue by mmalaq92** [jambonz/jambonz-feature-server#967]
Hi there,

I successfully installed and deployed Jambonz on AWS and configured the DNS settings, everything was working as expected. However, after installing the SSL certificate, I encountered an issue when trying to access the application through both the domain and IP address. The error message displayed is: "The server cannot be reached."
![1a75ed1a-667c-43c4-b64e-66715b42ec0c](https://github.com/user-attachments/assets/be1e6f0d-ed93-4cf4-98e2-5bef9277d0f6)

One important note: I am able to interact with Jambonz through the API (using Postman) without any issues, so the underlying service seems to be running correctly.

Could someone help me identify what might be causing this problem? It seems to be related to the SSL configuration, but I'm not sure what might be missing or misconfigured.

Thanks in advance for your assistance!

**Comment by davehorton** [comment]
Did you install on AWS using the AWS marketplace offering we provide?

**Comment by davehorton** [comment]
closed for lack of response
